/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Build New': '新建',
    'ON': '开启',
    'Options': '选项',
    'Periodically gain research points, which can be used to unlock unique upgrades from different research paths via the icons below.': '定期获得研究点数，可用于通过以下图标解锁来自不同研究路径的独特升级。',
    'Periodically merchants will drop a package that will grant a random bonus.': '商人会定期掉落一个包裹，该包裹将授予随机奖金。',
    'Power Plant': '发电厂',
    'Power Saver': '节电器',
    'Production': '生产',
    'Propaganda Center': '宣传中心',
    'Propaganda Centers increase the base production of all tier 1 buildings by 1500 per 10 propaganda centers, and all tier 2 buildings by 8000 per 10 propaganda centers.': '每 10 个宣传中心增加所有 1 级建筑 1500 的基础产量，每 10 个宣传中心增加所有 2 级建筑 8000 的基础产量。',
    'Research Center': '研究中心',
    'Reset': '重置',
    'Reseting now will grant': '现在重置将授予',
    'Reseting now will grant the following': '立即重置将授予以下权限',
    'Temple': '神庙',
    'Wipe Save': '擦除存档',
    'Yes': '是',
    'You can automate': '你可以自动化',
    'UPGRADES': '升级',
    'Tutorial': '教程',
    'Unlocks a clicking sub-game, that can unlock various upgrades and effects.': '解锁一个点击子游戏，可以解锁各种升级和效果。',
    'Alien Research Facilities slowly unlock unique upgrades every hour. This upgrade rate does not change with game speed.': '外星研究设施每小时都会缓慢解锁独特的升级。 这个升级率不会随着游戏速度而变化。',
    'Alien Research Facility': '外星研究设施',
    'Asteroid Miner': '小行星矿工',
    'Autosave': '自动保存',
    'Autoupgrade': '自动升级',
    'Background': '背景',
    'Bank': '银行',
    'Banks slowly increase production over time (1% per 20 minutes).': '银行会随着时间的推移缓慢增加产量（每 20 分钟增加 1%）。',
    'Bought Upgrades': '已购买升级',
    'Black Hole': '黑洞',
    'BUILDINGS': '建筑',
    'Choose': '选择',
    'Choose A Building To Unlock': '选择要解锁的建筑物',
    'Click Farm': '点击农场',
    'Click Farms grant the ability to place autoclickers that simulate real clicks anywhere on the screen once every 3 seconds. This is available with the blue mouse icon to the left of this menu.': '点击农场允许每 3 秒在屏幕上的任何位置放置模拟真实点击的自动点击器。 这可通过此菜单左侧的蓝色鼠标图标获得。',
    'Click one of the icons below to begin worshipping an Aztec deity. The longer a deity is worshipped the more powerful their bonuses will be up to a point.': '单击下面的图标之一开始崇拜阿兹特克神祇。 一个神被崇拜的时间越长，他们的奖励就越强大。',
    'Click the dice to gain a random bonus or loss based on how the die rolls. Gain 1 roll every 150 seconds.': '单击骰子以根据骰子的投掷方式获得随机奖励或损失。 每 150 秒获得 1 次掷骰。',
    'Cultist': '信徒',
    'Cultist generate blood that can be used to preform rituals. Click the blue a red icons to perform a ritual.': '信徒生成可用于执行仪式的血液。 单击蓝色和红色图标以执行仪式。',
    'Enter': '进入',
    'Gambler': '赌徒',
    'Generates energy, which can be used to activate various production boosting effects.': '产生能源，可用于激活各种生产促进效果。',
    'Import save': '导入存档',
    'Import/Export Save': '导入/导出存档',
    'Input': '输入',
    'karma points. Each karma point grants +1% production that does not disappear after resets.': '业力点。 每个业力点都会提供 +1% 的生产力，并且在重置后不会消失。',
    'Loading': '加载中',
    'LOADING': '加载中',
    'Merchant': '商人',
    'Mine': '矿山',
    'Mines slowly grant gold, which can be used in exchange for other buildings currencies.': '矿山慢慢产出黄金，可以用来换取其他建筑货币。',
    'Monospace Font': '面包车字体',
    'Never': '从不',
    'OFF': '关闭',
    'Sacrificial Shrine': '祭祀神殿',
    'Stock Exchange': '股票交易',
    'Stock markets value fluctuates over time, sometimes giving large production bonuses, and sometimes large production reductions.': '股票市场价值会随着时间的推移而波动，有时会提供大量生产奖金，有时会大幅减产。',
    'Sure?': '确定?',
    'tasks': '任务',
    'Asteroid Miners slowly increase their base production. This rate is increased for every 10 asteroid miners.': '小行星矿工缓慢地增加他们的基础产量。 每 10 个小行星矿工，这个比率就会增加。',
    'Error Console': '错误控制台',
    'Factories grant gears periodically, and these can be used to upgrade various stats via the gray icons below.': '工厂会定期生成齿轮，这些可用于通过下面的灰色图标升级各种统计数据。',
    'Frozen Wasteland': '冰封荒原',
    'Factory': '工厂',
    'Frozen Wastelands slowly produce snowflakes, that can be used for various effects. The generation rate does not change with the game speed.': '冰冻荒原会慢慢产生雪花，可以用于各种效果。 生成率不随游戏速度变化。',
    'Gold': '黄金',
    'Gold 1': '黄金 1',
    'Increases favor production by 1% per Worshipper': '每个崇拜者增加 1% 的青睐产量',
    'Increases normal production by 5% + 1% per reset.': '每次重置使正常产量提高 5% + 1%。',
    'Research': '研究',
    'Increases production by 5%.': '提高产量 5%。',
    'Increases research centers base production by 2.': '研究中心基础产量增加2。',
    'Increases the base production of factories by 1 every 2 minutes from now on.': '从现在开始每2分钟增加工厂的基础产量 1。',
    'Increases the base production of mines by 1 every 2 minutes from now on.': '从现在开始每 2 分钟增加矿山的基础产量 1。',
    'Increases the base production of research centers by 1 every 2 minutes from now on.': '从现在开始每2分钟增加研究中心的基础产量 1。',
    'Increases the base production of stock markets by 1 every 2 minutes from now on.': '从现在开始每2分钟增加股票市场的基础产量 1。',
    'Loaded Dice': '加载骰子',
    'Lower Wages': '降低工资',
    'Mad Scientists': '疯狂科学家',
    'Mutual Funds': '共同基金',
    'Free': '免费',
    'Requires': '需要',
    'Shorter Breaks': '更短的休息时间',
    'Six hours later': '六小时后',
    'Stock': '股票',
    'Temporal Mastery': '时间精通',
    'Time For Genius': '天才的时间',
    'Time For Gold': '黄金时间',
    'Time For Labor': '劳动时间',
    'Time To Mine': '采矿时间',
    'Trading Post': '贸易站',
    'Two hours later': '两小时后',
    'Unlocks the ability to automate simple tasks.': '解锁自动执行简单任务的能力。',
    'Unlocks the ability to change the passage of time.': '解锁改变时间流逝的能力。',
    'Allows you to exchange building currencies for different goods.': '允许您为不同的商品交换建筑货币。',
    'Autoclicker': '自动点击器',
    'Automation': '自动化',
    'Bet on Black': '投注黑色',
    'Building Resources': '建筑资源',
    'Charging Bull': '华尔街铜牛',
    'Cheap Labor': '廉价劳动力',
    'Click Combo': '点击组合',
    'Click to change various aspects of the game.': '点击以更改游戏的各个方面。',
    'Click to save.': '点击保存。',
    'Click to toggle autoclicking. If on the game will autoclick twice per second. This will disable all regular clicks and will not occur when normal clicks cannot occur (being in a different tab or similar).': '点击以切换自动点击。 如果在游戏中会每秒自动点击两次。 这将禁用所有常规点击，并且不会在无法发生正常点击（在不同的选项卡或类似选项卡中）时发生。',
    'Click to view all upgrades bought separated into 4 distinct categories.': '点击以查看分为 4 个不同类别的所有购买升级。',
    'Click to view various statistics and graphs about your game-play.': '点击以查看有关您的游戏的各种统计数据和图表。',
    'Clock Ticks': '时钟刻度',
    'Counterfeit Quarters': '伪造宿舍',
    'Davy Lamp': '戴维灯',
    'Deeper Mines': '更深的矿山',
    'Each tick is worth 1 second and can be used to speed up the game. Gain ticks while this game is closed. Click to change game speed.': '每个刻度值 1 秒，可用于加快游戏速度。 在此游戏关闭时获得滴答声。 单击以更改游戏速度。',
    'Eight hours later': '八小时后',
    'Every 100 real clicks increases production by 1%. This caps out at 100%.': '每 100 次实际点击将生产增加 1%。 这上限为 100%。',
    'Fearless Girl': '无畏的女孩',
    'Four hours later': '四小时后',
    'Gambling Mice': '赌博老鼠',
    'Gearsplosion': '齿轮爆炸',
    'Genius Mice': '天才老鼠',
    'Grants 10 ticks every time stocks markets reaches peak market value.': '每次股票市场达到最高市值时授予 10 个时刻。',
    'Grinding Gears': '磨齿轮',
    'Improved Clicking': '改进点击',
    'Increased Machanization': '提高机械化',
    'Increases base clicking reward by 1% of total production.': '将基本点击奖励提高总产量的 1%。',
    'Increases clicking reward by 1% of total production.': '将点击奖励提高总产量的 1%。',
    'Increases max blood by 50.': '最大血量增加 50。',
    'Increases production based on total time spent playing.': '根据游戏总时间增加产量。',
    'Increases production by 0.04% for each roll activated.': '每激活一投掷，产量提高 0.04%。',
    'Increases total production by 15%.': '将总产量提高 15%。',
    'Investing Mice': '投资老鼠',
    'Just Beginning': '刚开始',
    'Mensa': '笨蛋',
    'Mining Mice': '采矿老鼠',
    'Metal Mouse': '金属鼠标',
    'Opens the Trade menu.': '打开交易菜单。',
    'Permanently increases clicking reward by 0.2%.': '永久增加点击奖励 0.2%。',
    'Permanently increases maximum game speed by 1.': '永久性地将最大游戏速度提高 1。',
    'Permanently increases production by 1%.': '永久增加 1% 的产量。',
    'Refill Dice': '填充骰子',
    'Secert Labrotories': '秘密实验室',
    'Slave Mice': '奴隶老鼠',
    'Synergy': '协同作用',
    'Time Boost': '时间提升',
    'Trading Menu': '交易菜单',
    'Unlocks an upgrade that improves specific buildings.': '解锁可改善特定建筑的升级。',
    'Unlocks an upgrade that increases production in some form.': '解锁以某种形式增加产量的升级。',
    'Unlocks an upgrade that increases the productivity of research centers.': '解锁可提高研究中心生产力的升级。',
    'Utility': '效用',
    'Advanced Dice': '高级骰子',
    'Advanced Gears': '高级齿轮',
    'Advanced Markets': '高级市场',
    'Advanced Mining': '高级矿山',
    'Augmented Clicking': '强化点击',
    'Automation Boost': '自动提升',
    'Basic Dice': '基础骰子',
    'Basic Gears': '基础齿轮',
    'Basic Markets': '基础市场',
    'Basic Mining': '基础矿山',
    'Basic Research': '基础研究',
    'Boxcars': '棚车',
    'Click Boost': '点击提升',
    'Click Workers': '点击工人',
    'Clicking reward is increased by 0.5 for every other previous click, this effect is increased for every 10 mines owned.': '之前每点击一次点击奖励增加 0.5，每拥有 10 个矿山增加此效果。',
    'Clicking reward is increased by 5 per research center.': '每个研究中心点击奖励增加5。',
    'Conveyor Belts': '传送带',
    'Decreaes production by 33%.': '产量减少 33%。',
    'Decreases gear time by 10 seconds.': '齿轮时间减少 10 秒。',
    'Decreases mine time by 4 minutes.': '将采矿时间减少 4 分钟。',
    'Deep Mines': '深矿',
    'Each real click decreases the amount of time left to mine a gold bar by 1 second. This cannot occur more than 60 times a minute.': '每次真正的点击都会将挖掘金条的剩余时间减少 1 秒。 这种情况每分钟不能超过 60 次。',
    'Every 10 real clicks decreases the amount of time to obtain the next roll by 2 seconds.': '每 10 次真正的点击会减少 2 秒获得下一个投掷的时间。',
    'Every 100 clicks increases factories base production by 1.': '每点击 100 次，工厂基础产量就会增加 1。',
    'Every 100 clicks increases gambers base production by 1.': '每点击 100 次，赌徒 基础产量就会增加 1。',
    'Every 100 clicks increases mines base production by 1.': '每点击 100 次，矿山基础产量就会增加 1。',
    'Every 100 clicks increases research centers base production by 1.': '每点击 100 次，研究中心的基础产量就会增加 1。',
    'Every 100 clicks increases stock markets base production by 1.': '每点击 100 次，股票市场基础产量就会增加 1。',
    'Exchange 1 gold for a dice refill.': '用 1 金币换取一个填充骰子。',
    'Extreme Clicking': '极端点击',
    'Flynn Effect': '弗林效应',
    'Fountain of Blood': '血之泉',
    'Futuristic Production': '未来生产',
    '5: No Effect': '5: 无效果',
    '6: 2 extra rolls': '6：2次额外的投掷',
    'Increases production by 10%, this bonus is amplified based on how many buildings are owned.': '将产量提高 10%，此奖励会根据拥有的建筑物数量而放大。',
    'Instantly grants 10 gold': '立即授予 10 黄金',
    'Piles of Gold': '成堆的黄金',
    'Bountiful Construction': '丰富多样的建筑',
    'Advanced Research': '高级研究',
    'Better Drills': '更好地钻',
    'Dice': '骰子',
    'Doubles total production of your gamblers.': '赌徒的总产量翻倍。',
    'Every 2 clicks decreases the amount of time until the next research point is gained by 1.': '每点击 2 次，下一个研究点的时间就会减少 1。',
    'Experienced Gamblers': '经验丰富的赌徒',
    'Get 2 extra rolls when rolling boxcars.': '投掷棚车时获得 2 个额外的投掷。',
    'Increases production by 0.05% per research center.': '每个研究中心的产量提高 0.05%。',
    'Increases the base production of gamblers by 1 every 2 minutes from now on.': '从现在开始每 2 分钟将赌徒的基础产量增加 1。',
    'Mechanical Enchacements': '机械增强',
    'Proper laboratory Attire': '合适的实验室着装',
    'Snake Eyes': '蛇眼',
    'Time For Gambling': '赌徒时间',
    'Adding On': '增加',
    'Union Busters': '联盟克星',
    'Cultist generate blood that can be used to preform rituals.': '邪教徒生成可用于执行仪式的血液。',
    'Temples allow you to worship an ancient Aztec god, granting a bonus from this.': '神庙允许您崇拜古代阿兹特克神，从而获得奖励。',
    'Click build new to choose a building to unlock, which will slowly produce cash.': '点击新建，选择一栋建筑解锁，会慢慢产出现金。',
    'Each building has a unique aspect which can be accessed through the black and white icon beside the building. Open it.': '每个建筑都有一个独特的方面，可以通过建筑旁边的黑白图标访问。 打开它。',
    'Factories slowly grants gears which can be used to boost various aspects of gameplay.': '工厂会慢慢授予齿轮，可用于提升游戏玩法的各个方面。',
    'Gamblers slowly produce dice that can be used for random benefits or losses.': '赌徒慢慢产生可用于随机收益或损失的骰子。',
    'Inside each building\'s menu is a description of the building, statistics for that building, and for most buildings some form of interactivity. Close the menu by clicking the black and white icon again.': '每个建筑物的菜单内都有建筑物的描述、该建筑物的统计数据以及大多数建筑物的某种形式的交互。 再次单击黑白图标关闭菜单。',
    'Research centers very slowly unlock new upgrades.': '研究中心非常缓慢地解锁新的升级。',
    'Select one': '选择一个',
    'Stock exchanges change production based on how the market is doing.': '证券交易所根据市场走势改变生产。',
    'To begin click on the globe to obtain cash (5 times).': '开始点击地球获取现金（5 次）。',
    'Mines very slowly grant gold, which can be used in exchange for other currencies.': '矿山非常缓慢地授予黄金，可以用来换取其他货币。',
    'Alien Research Facilities slowly unlock unique upgrades every hour. The upgrade rate does not change with game speed.': '外星研究设施每小时都会缓慢解锁独特的升级。 升级速度不随游戏速度变化。',
    'Asteroid miners have a high base production that increases over time.': '小行星矿工的基础产量很高，而且会随着时间的推移而增加。',
    'Banks have high base production, and slowly increase production over time.': '银行的基础产量很高，随着时间的推移，产量会慢慢增加。',
    'Click farms grants the ability to place autoclickers that simulate real clicks anywhere on the screen.': '点击农场允许在屏幕上的任何地方放置模拟真实点击的自动点击器。',
    'Countless upgrades that improve various aspects of production can be found in the upgrades menu. Buy the upgrade Improved Clicking.': '在升级菜单中可以找到无数改进生产各个方面的升级。 购买升级改进点击。',
    'Frozen Wastelands slowly produce snowflakes that can be used for various effects. The generation rate does not change with the game speed.': '冰冻荒原会慢慢产生可用于各种效果的雪花。 生成率不随游戏速度变化。',
    'Power Plants slowly produce energy that can be used to gain production bonuses.': '发电厂缓慢地产生可用于获得生产奖金的能量。',
    'Gilded Profits': '镀金利润',
    'Gold for Progress': '黄金进展',
    'Golden Boost': '金色提升',
    'Golden Upgrade"': '金色升级',
    'Has a 20% change to drain all blood and create a free cultist': '有 20% 的几率来吸取所有血液并创建一个免费的邪教徒',
    'Increaes the maximum favor obtainable by 50%.': '将可获得的最大青睐提高 50%。',
    'Increases max blood by 1 per 5 temples, and increases the base production of temples by 4 per cultist.': '每 5 个神殿增加 1 最大血量，每个邪教徒增加 4 神殿的基础产量。',
    'Increases max rolls by 2.': '将最大掷骰增加 2。',
    'Increases production by 0.05% for each ritual activated.': '每个激活的仪式使产量提高 0.05%。',
    'Increases production by 0.1% per stock market.': '每个股票市场的产量增加 0.1%。',
    'Increases production by 75% for 3 minutes.': '在 3 分钟内将产量提高 75%。',
    'Increases the base production of cultists by 1 every 2 minutes from now on.': '从现在开始每 2 分钟增加 1 个邪教徒的基础产量。',
    'Increases the production of each factory by 6 per factory.': '每个工厂的产量增加 6 个。',
    'Increases the production of each gambler by 8 per factory, and vice versa.': '每家工厂每名赌徒的产量增加 8，反之亦然。',
    'Increases the time bonuses last for by 20%.': '将持续时间加成提高 20%。',
    'Instantly Gain 5 free cultists.': '立即获得 5 个免费邪教徒。',
    'Itelligence Booster': '智能助推器',
    'Koresh Leadership': '科雷什领导力',
    'Loan Sharks': '高利贷',
    'Luck For Luck': '幸运的运气',
    'Machine for Clicks': '点击机器',
    'Machine for Machine': '机器换机器',
    'Machine for Profits': '利润机器',
    'Mechanized Machine Making': '机械化机械制造',
    'Money Mining': '货币开采',
    'Mysterious Tablet': '神秘平板电脑',
    'NHS Meeting': 'NHS会议',
    'Occult Construction': '神秘建筑',
    'Occult Subsidies': '神秘补贴',
    'Packing Tape': '包装胶布',
    'Permanently increases cultist base production by 0.25': '永久增加邪教徒基地产量 0.25',
    'Permanently increases production by 2': '永久增加产量 2',
    'Refill Blood': '补充血液',
    'Ritual Sacrifice': '祭祀',
    'Robotic Replacements': '机器人更换',
    'Smart Fingers': '智能手指',
    'Stock Markets decrease mine times, and increases the max market value by 1% per 5 Mines.': '股票市场减少了挖矿次数，并且每 5 个挖矿增加了 1% 的最大市值。',
    'Temporarily increases production by 75% for 66 seconds': '暂时将产量提高 75%，持续 66 秒',
    'Texan Ranch': '德克萨斯牧场',
    'The Big Idea': '大创意',
    'The Brick': '砖头',
    'The House': '房子',
    'Time For Sacrifice': '牺牲时间',
    'Trade 1 blood container for 10% production boost for 10 minutes. This percentage can stack, but not the time.': '用 1 个血液容器换取 10% 的产量提升，持续 10 分钟。 这个百分比可以叠加，但不是时间。',
    'Trade 1 gold bar for a permanent 1% bonus to production.': '交易 1 条金条可获得 1% 的永久生产奖励。',
    'Trade 120 Blood for 1 Blood Container.': '用 120 血换 1 个血液容器。',
    'Trade 2 blood containers for a permanent 1% bonus to production.': '交易 2 个血液容器以获得 1% 的永久性生产奖励。',
    'Trade 2 clovers for a permanent 1% bonus to production.': '交易 2 棵三叶草，可获得 1% 的永久生产奖励。',
    'Trade 2 clovers to have a 50% chance to double production for 3 minutes, and a 50% chance to remove all current beneficial effects. This percentage can stack, but not the time.': '交易 2 片三叶草有 50% 的几率使产量翻倍，持续 3 分钟，并有 50% 的几率消除所有当前的有益效果。 这个百分比可以叠加，但不是时间。',
    'Trade 2 gold bars for 1 research point.': '用 2 个金条换取 1 个研究点。',
    'Trade 2 gold bars for an upgrade.': '交易 2 根金条进行升级。',
    'Trade 2 machine frames for a permanent 1% production bonus': '交易 2 个机器框架以获得 1% 的永久生产奖励',
    'Trade 20 gears for 1 machine frames.': '用 20 个齿轮换取 1 个机器框架。',
    'Trade 20 machine frames for 1 autoclick per second': '以每秒 1 次自动点击的价格交易 20 个机器帧',
    'Trade 5 dice rolls for a four leaf clover.': '用 5 个骰子卷换取 1 个四叶草。',
    'Trade 8 blood containers for an upgrade.': '交易 8 个血容器来升级。',
    'Trade 8 clovers for an upgrade.': '交易 8 片三叶草进行升级。',
    'Trade Routes': '贸易路线',
    'Trade Secrets': '商业机密',
    'Unorthodox': '非正统',
    'Trickle Down Economics': '下渗经济学',
    'Upgrade': '升级',
    'Waco Headquarters': '韦科总部',
    'Blood for Blood': '血债血偿',
    'Bloody Boost': '血腥提升',
    'Bloody Upgrade': '血腥升级',
    'Boost': '提升',
    'Bountiful Blood': '丰饶之血',
    'Double Down': '双降',
    'Double Drop': '双倍掉落',
    'Double Gears': '双倍齿轮',
    'Double Stacks': '双堆栈',
    'Doubles the production of cultists.': '邪教徒的产量翻倍。',
    'Doubles the production of factories.': '工厂产量翻倍。',
    'Doubles the production of gamblers.': '赌徒产量翻倍。',
    'Doubles the production of stock markets.': '使股票市场的产量翻倍。',
    'Each research point gained from now on increases production by 1%.': '从现在开始，每获得一个研究点都会增加 1% 的产量。',
    'Endless Epiphany': '无尽的顿悟',
    'Feast or Famine': '盛宴或饥荒',
    'Blood Rush': '热血冲刺',
    'Bloody Timing': '血腥时刻',
    'Exchange 1 gold for a 15 gears.': '1 金币换 15 齿轮。',
    'Refill Gears': '补充齿轮',
    'Generates 40 ticks.': '产生 40 时刻。',
    'Economic Bubble': '经济泡沫',
    'Euchre': '欺骗',
    'Evening Star': '晚星',
    'Every 100 clicks increases cultist base production by 1.': '每点击 100 次，邪教徒基地产量就会增加 1。',
    'Every 100 clicks increases temples base production by 1.': '每点击 100 次，寺庙的基础产量就会增加 1。',
    'Every 2 research centers increases production by 0.2%.': '每 2 个研究中心增加 0.2% 的产量。',
    'Every 60 gears obtained increases production by 1%.': '每获得 60 个齿轮，产量就会增加 1%。',
    'Every real 10 clicks grants an additional tick.': '每真正的 10 次点击都会授予一个额外的时刻。',
    'Factory Function': '工厂函数',
    'Faster Factories': '更快的工厂',
    'Faster Production': '更快的生产',
    'Favor of Huitzilopochtli': '惠齐洛波奇特利的青睐',
    'Fourteen hours later': '十四小时后',
    'Gain 1 4-leaf clover every hour.': '每小时获得 1 个 4 叶三叶草。',
    'Gain 1 Blood Capsule every hour.': '每小时获得 1 个血胶囊。',
    'Gain 1 machine frame every hour.': '每小时获得1个机器帧。',
    'Gain research points 4 Minutes Faster.': '更快获得研究点数 4 分钟。',
    'Gambling Addiction': '赌博成瘾',
    'Increases production by 0.1% per cultist.': '每个邪教徒的产量提高 0.1%。',
    'Instantly grants 1 gold, but brings down a terrible wrath in retribution. Only can be activated when highly favored.': '立即获得 1 金币，但会在报应中带来可怕的愤怒。 只有在受到高度青睐时才能激活。',
    'Like Clockwork': '有规律的',
    'Liquid Time': '流动时间',
    'Moore Research': '更更多研究',
    'Morning Star': '晨星',
    'Opens the menu for automation.': '打开自动化菜单。',
    'Opens the Temporal Mastery menu.': '打开时间精通菜单。',
    'Pok a Tok': '叽叽歪歪',
    'Quick Creativity': '快速创新',
    'Religious Festivals': '宗教节日',
    'Robotic Miners': '机器人矿工',
    'Steal Idol.': '偷偶像',
    'Temporal Menu': '临时菜单',
    'Ten hours later': '十小时后',
    'Twelve hours later': '十二小时后',
    'Worship Huitzilopochtli': '崇拜维齐洛波奇特利',
    'Worship Quetzalcoatl': '崇拜羽蛇神',
    'Worship Tezcatlipoca': '崇拜特斯卡特利波卡',
    'Worship Tlaloc': '崇拜特拉洛克',
    'Worshipping Huitzilopochtli will increases the value of your clicks by up to 10%, and slowly grants his favor.': '崇拜 维齐洛波奇特利 将使您的点击价值增加多达 10%，并慢慢获得他的青睐。',
    'Worshipping Quetzalcoatl reduces the cost of buildings by up to 10%, and slowly grants his favor.': '崇拜羽蛇神最多可以降低建筑成本 10%，并慢慢获得他的青睐。',
    'Worshipping Tezcatlipoca increases the speed of the game by up to 10%, and slowly grants his favor.': '崇拜特斯卡特利波卡最多可以提高10%的游戏速度，并慢慢获得他的青睐。',
    'Worshipping Tlaloc increases total production by up to 10%, and slowly grants his favor.': '崇拜特拉洛克可使总产量最多提高 10%，并慢慢获得他的青睐。',
    'Huitzilopochtli': '维齐洛波奇特利',
    'Additional Clicks': '额外点击次数',
    'Advanced Worship': '进阶崇拜',
    'Autoclicks once per second.': '每秒自动点击一次。',
    'Automation Menu': '自动化菜单',
    'Basic Worship': '基础崇拜',
    'Clicking reward is increased by 4 per temple.': '每个神庙点击奖励增加 4。',
    'Decreases building costs by 5%.': '建筑成本降低 5%。',
    'Decreases the amount of time mines take to generate gold by 3 minutes.': '将矿山生成黄金所需的时间减少 3 分钟。',
    'Decreases the time it takes factories to generate gears by 5 seconds.': '将工厂生成齿轮所需的时间减少 5 秒。',
    'Devoted Mice': '虔诚的老鼠',
    'Discount Time': '折扣时间',
    'Double Idolatry': '双重偶像',
    'Doubles the production of temples.': '神庙产量翻倍。',
    'Duel Worship': '决斗崇拜',
    'Gold Vault': '金库',
    'Increases the base production of temples by 1 every 2 minutes from now on.': '从现在开始每2分钟增加1个寺庙的基础产量。',
    'Sixteen hours later': '十六小时后',
    'Time For Worship': '崇拜时间',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Gold: ": "黄金: ",
    "Production Bonus: ": "生产奖励: ",
    "Production: ": "生产: ",
    "Ritual Bonus: ": "仪式奖励：",
    "Total Rituals: ": "总计仪式: ",
    "Total Rolls: ": "总计投掷: ",
    "Version ": "版本 ",
    "Autobuy": "自动购买",
    "Autoclicks per second": "每秒自动点击次数",
    "Click Bonus: ": "点击奖励: ",
    "Current Roll: ": "当前卷轴: ",
    "Gambling Bonus: ": "赌徒奖励: ",
    "Gears Obtained: ": "获得的齿轮：",
    "Gold Mined: ": "开采的黄金：",
    "Last Roll: ": "最近卷轴: ",
    "Market Bonus: ": "市场奖励: ",
    "Max Blood: ": "最大血液: ",
    "Blood: ": "血液: ",
    "Max Time Bonus: ": "最大时间奖励: ",
    "Total Buildings: ": "总建筑量：",
    "Total Clicks: ": "总点击数: ",
    "Total Real Clicks: ": "总真实点击数: ",
    "Total Real Time: ": "总真实时间: ",
    "Total Time: ": "总时间: ",
    "Total Upgrades: ": "总升级: ",
    "Click Bonus ": "点击奖励 ",
    "Max Time Bonus ": "最大时间奖励 ",
    "Power: ": "力量: ",
    "Price: ": "价格: ",
    "Research Points: ": "研究点: ",
    "Rolls: ": "投掷: ",
    "Snowballs ": "雪球 ",
    "Gears: ": "齿轮: ",
    "Futuristic Production Mk ": "未来生产Mk ",
    "Hotkey: ": "快捷键: ",
    "Lucky ": "幸运 ",
    "Unlucky ": "不幸 ",
    "Click Workers Mk ": "点击工人 Mk ",
    "Base Production: ": "基础产量: ",
    "Increased Machanization Mk ": "增加机械化 Mk",
    "Mechanical Enchacements Mk ": "机械强化 Mk",
    "Production bonus: ": "生产加成: ",
    "Worshipping: ": "崇拜: ",
    "Bountiful Construction Mk ": "丰富的建筑 Mk",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    'Buy up to': '批量购买',
    " ✓": " ✓",
    " X": " X",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) Trillion p$/,
    /^([\d\.]+) Million p$/,
    /^([\d\.]+) Billion p$/,
    /^([\d\.]+) Trillion$/,
    /^([\d\.]+) Million$/,
    /^([\d\.]+) Billion$/,
    /^([\d\.]+) p$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Increases total production by (.+)\%, and increases stock exchanges base production by (.+).$/, '总产量增加 $1\%，股票市场基础产量增加 $2。'],
    [/^Increases mines base production by (.+).$/, '增加矿山基础产量 $1。'],
    [/^Increases gamblers base production by (.+).$/, '增加赌徒基础产量 $1。'],
    [/^Increases factories base production by (.+).$/, '增加工厂基础产量 $1。'],
    [/^Increases base clicking reward by ([\d\.,]+).$/, '将基础点击奖励提高 $1。'],
    [/^Increases temples base production by ([\d\.,]+).$/, '增加寺庙基础产量 $1。'],
    [/^Increases research centers base production by ([\d\.,]+).$/, '将研究中心基础产量增加 $1。'],
    [/^Increases cultist base production by ([\d\.,]+).$/, '将研究中心基础产量增加 $1。'],
    [/^Increases production by ([\d\.,]+)\%.$/, '提高产量 $1\%。'],
    [/^Cost: (.+) Research Points$/, '成本: $1 研究点'],
    [/^Cost: (.+) Blood.$/, '成本: $1 血液。'],
    [/^Cost: (.+) Gears.$/, '成本: $1 齿轮。'],
    [/^Cost: (.+) favor$/, '成本: $1 青睐'],
    [/^Cost: (.+) \((.+)x$/, '成本: $1 \($2x'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^Gold ([\d\.]+)$/, '黄金 $1'],
	[/^([\d\.]+): (.+) production permanently$/, '$1: $2 永久生产'],
	[/^([\d\.]+): (.+) production$/, '$1: $2 生产'],
	[/^([\d\.,]+)\/([\d\.,]+) Rolls$/, '$1\/$2 投掷'],
	[/^([\d\.,]+)s left$/, '剩余 $1 秒'],
	[/^([\d\.,]+) Gears$/, '$1 齿轮'],
	[/^([\d\.,]+) Factories$/, '$1 工厂'],
	[/^([\d\.,]+) Temples$/, '$1 神庙'],
	[/^([\d\.,]+) Stock Exchanges$/, '$1 股票市场'],
	[/^([\d\.,]+) Gamblers$/, '$1 赌徒'],
	[/^([\d\.,]+) Cultists$/, '$1 邪教徒'],
	[/^([\d\.,]+) Gold$/, '$1 黄金'],
	[/^([\d\.,]+) Research Points$/, '$1 研究点'],
	[/^([\d\.]+) Karma Points$/, '$1 业力点数'],
	[/^([\d\.]+) Karma Points$/, '$1 业力点数'],
	[/^([\d\.]+) Quadrillion$/, '$1 Quadrillion'],
	[/^([\d\.]+) Octillion$/, '$1 Octillion'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);