/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Build New': '新建',
    'ON': '开启',
    'Options': '选项',
    'Periodically gain research points, which can be used to unlock unique upgrades from different research paths via the icons below.': '定期获得研究点数，可用于通过以下图标解锁来自不同研究路径的独特升级。',
    'Periodically merchants will drop a package that will grant a random bonus.': '商人会定期掉落一个包裹，该包裹将授予随机奖金。',
    'Power Plant': '发电厂',
    'Power Saver': '节电器',
    'Production': '生产',
    'Propaganda Center': '宣传中心',
    'Propaganda Centers increase the base production of all tier 1 buildings by 1500 per 10 propaganda centers, and all tier 2 buildings by 8000 per 10 propaganda centers.': '每 10 个宣传中心增加所有 1 级建筑 1500 的基础产量，每 10 个宣传中心增加所有 2 级建筑 8000 的基础产量。',
    'Research Center': '研究中心',
    'Reset': '重置',
    'Reseting now will grant': '现在重置将授予',
    'Reseting now will grant the following': '立即重置将授予以下权限',
    'Temple': '神庙',
    'Wipe Save': '擦除存档',
    'Yes': '是',
    'You can automate': '你可以自动化',
    'UPGRADES': '升级',
    'Tutorial': '教程',
    'Unlocks a clicking sub-game, that can unlock various upgrades and effects.': '解锁一个点击子游戏，可以解锁各种升级和效果。',
    ' Buy up to': '最多买',
    'Alien Research Facilities slowly unlock unique upgrades every hour. This upgrade rate does not change with game speed.': '外星研究设施每小时都会缓慢解锁独特的升级。 这个升级率不会随着游戏速度而变化。',
    'Alien Research Facility': '外星研究设施',
    'Asteroid Miner': '小行星矿工',
    'Autosave': '自动保存',
    'Autoupgrade': '自动升级',
    'Background': '背景',
    'Bank': '银行',
    'Banks slowly increase production over time (1% per 20 minutes).': '银行会随着时间的推移缓慢增加产量（每 20 分钟增加 1%）。',
    'Bought Upgrades': '已购买升级',
    'Black Hole': '黑洞',
    'BUILDINGS': '建筑',
    'Choose': '选择',
    'Choose A Building To Unlock': '选择要解锁的建筑物',
    'Click Farm': '点击农场',
    'Click Farms grant the ability to place autoclickers that simulate real clicks anywhere on the screen once every 3 seconds. This is available with the blue mouse icon to the left of this menu.': '点击农场允许每 3 秒在屏幕上的任何位置放置模拟真实点击的自动点击器。 这可通过此菜单左侧的蓝色鼠标图标获得。',
    'Click one of the icons below to begin worshipping an Aztec deity. The longer a deity is worshipped the more powerful their bonuses will be up to a point.': '单击下面的图标之一开始崇拜阿兹特克神祇。 一个神被崇拜的时间越长，他们的奖励就越强大。',
    'Click the dice to gain a random bonus or loss based on how the die rolls. Gain 1 roll every 150 seconds.': '单击骰子以根据骰子的滚动方式获得随机奖励或损失。 每 150 秒获得 1 次掷骰。',
    'Cultist': '信徒',
    'Cultist generate blood that can be used to preform rituals. Click the blue a red icons to perform a ritual.': '信徒生成可用于执行仪式的血液。 单击蓝色和红色图标以执行仪式。',
    'Enter': '进入',
    'Gambler': '赌徒',
    'Generates energy, which can be used to activate various production boosting effects.': '产生能源，可用于激活各种生产促进效果。',
    'Import save': '导入存档',
    'Import/Export Save': '导入/导出存档',
    'Input': '输入',
    'karma points. Each karma point grants +1% production that does not disappear after resets.': '业力点。 每个业力点都会提供 +1% 的生产力，并且在重置后不会消失。',
    'Loading': '加载中',
    'LOADING': '加载中',
    'Merchant': '商人',
    'Mine': '矿山',
    'Mines slowly grant gold, which can be used in exchange for other buildings currencies.': '矿山慢慢产出黄金，可以用来换取其他建筑货币。',
    'Monospace Font': '面包车字体',
    'Never': '从不',
    'OFF': '关闭',
    'Sacrificial Shrine': '祭祀神殿',
    'Stock Exchange': '股票交易',
    'Stock markets value fluctuates over time, sometimes giving large production bonuses, and sometimes large production reductions.': '股票市场价值会随着时间的推移而波动，有时会提供大量生产奖金，有时会大幅减产。',
    'Sure?': '确定?',
    'tasks': '任务',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Gold: ": "黄金: ",
    "Production Bonus: ": "生产奖励: ",
    "Production: ": "生产: ",
    "Ritual Bonus: ": "仪式奖励：",
    "Total Rituals: ": "总计仪式: ",
    "Total Rolls: ": "总计卷轴: ",
    "Version ": "版本 ",
    "Autobuy": "自动购买",
    "Autoclicks per second": "每秒自动点击次数",
    "Click Bonus: ": "点击奖励: ",
    "Current Roll: ": "当前卷轴: ",
    "Gambling Bonus: ": "赌徒奖励: ",
    "Gears Obtained: ": "获得的齿轮：",
    "Gold Mined: ": "开采的黄金：",
    "Last Roll: ": "最近卷轴: ",
    "Market Bonus: ": "市场奖励: ",
    "Max Blood: ": "最大血液: ",
    "Blood: ": "血液: ",
    "Max Time Bonus: ": "最大时间奖励: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Cost: (.+) favor$/, '成本: $1 人情'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+) Research Points$/, '$1 研究点'],
	[/^([\d\.]+) Karma Points$/, '$1 业力点数'],
	[/^([\d\.]+) Quadrillion$/, '$1 Quadrillion'],
	[/^([\d\.]+) Octillion$/, '$1 Octillion'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);