upgrade_defs = [];

function createUpgrade(id, x, y, name, tooltip, cost, callback, formula, category, tooltip_value) {
   var self = {
		id : id,
		name: name,
		x: x,
		y: y,
		cost: cost,
		tooltip: tooltip,
		callback: callback,
		formula: formula,
		bought: false,
		available: false,
		
		buy: function(){
			if (window.gold >= this.cost && !this.bought) {	
				window.gold -= this.cost;
				this.bought = true;
				this.callback();
				updateUpgrades();
				hideTooltip();
			}
		}
  };
  if (typeof category != 'undefined') {self.category = category}
  if (tooltip_value) {self.tooltip_value = tooltip_value}
  return self;
}

function initUpgrades() { 
	/* 0 */upgrade_defs.push(createUpgrade('ele_mouse_1', 0, 10, 'Improved Clicking', 'Increases base clicking reward by 3.<br/><span class="price">Price: 20</span>', 20, function() {}, function() {click_production_base+=3}, 1));
	/* 1 */upgrade_defs.push(createUpgrade('loaded_dice', 0, 1, 'Loaded Dice', 'Increases gamblers base production by 2.<br/><span class="price">Price: 750</span>', 750, function() {}, function() {building_defs[0].base_production += 2}, 0));
	/* 2 */upgrade_defs.push(createUpgrade('counterfeit_quarters', 1, 1, 'Counterfeit Quarters', 'Increases gamblers base production by 8.<br/><span class="price">Price: 10000</span>', 10000, function() {}, function() {building_defs[0].base_production += 8}, 0));
	/* 3 */upgrade_defs.push(createUpgrade('bet_on_black', 2, 1, 'Bet on Black', 'Increases gamblers base production by 20.<br/><span class="price">Price: 2 Million</span>', 2000000, function() {}, function() {building_defs[0].base_production += 20}, 0));
	/* 4 */upgrade_defs.push(createUpgrade('adding_on', 3, 1, 'Adding On', 'Increases gamblers base production by 50.<br/><span class="price">Price: 200 Million</span>', 200000000, function() {}, function() {building_defs[0].base_production += 50}, 0));
	/* 5 */upgrade_defs.push(createUpgrade('euchre', 4, 1, 'Euchre', 'Increases gamblers base production by 200.<br/><span class="price">Price: 30 Billion</span>', 30000000000, function() {}, function() {building_defs[0].base_production += 200}, 0));
	/* 6 */upgrade_defs.push(createUpgrade('blackjack', 5, 1, 'Blackjack', 'Increases gamblers base production by 1000.<br/><span class="price">Price: 300 Trillion</span>', 300000000000000, function() {}, function() {building_defs[0].base_production += 1000}, 0));
	/* 7 */upgrade_defs.push(createUpgrade('snake_eyes_up', 6, 1, 'Snake Eyes', 'Increases total production by 15%.<br/><span class="price">Price: 10000</span>', 10000, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 8 */upgrade_defs.push(createUpgrade('lucky_dice_up', 7, 1, 'Lucky Dice', 'Get 2 extra rolls when rolling boxcars.<br/><span class="price">Price: 50000</span>', 50000, function() {}, function() {}, 2));
	/* 9 */upgrade_defs.push(createUpgrade('experienced_gamblers', 8, 1, 'Experienced Gamblers', 'Doubles total production of your gamblers.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {building_defs[0].production_multiplier *= 2}, 2));
	/* 10 */upgrade_defs.push(createUpgrade('the_house', 9, 1, 'The House', 'Increases total production by 15%.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 11 */upgrade_defs.push(createUpgrade('unorthodox', 0, 2, 'Unorthodox', 'Increases cultist base production by 2.<br/><span class="price">Price: 1000</span>', 1000, function() {}, function() {building_defs[1].base_production += 2}, 0));
	/* 12 */upgrade_defs.push(createUpgrade('mysterious_tablet', 1, 2, 'Mysterious Tablet', 'Increases cultist base production by 8.<br/><span class="price">Price: 15000</span>', 15000, function() {}, function() {building_defs[1].base_production += 8}, 0));
	/* 13 */upgrade_defs.push(createUpgrade('koresh_leadership', 2, 2, 'Koresh Leadership', 'Increases cultist base production by 18.<br/><span class="price">Price: 3 Million</span>', 3000000, function() {}, function() {building_defs[1].base_production += 18}, 0));
	/* 14 */upgrade_defs.push(createUpgrade('texan_ranch', 3, 2, 'Texan Ranch', 'Increases cultist base production by 40.<br/><span class="price">Price: 300 Million</span>', 300000000, function() {}, function() {building_defs[1].base_production += 40}, 0));
	/* 15 */upgrade_defs.push(createUpgrade('waco_headquarters', 4, 2, 'Waco Headquarters', 'Increases cultist base production by 160.<br/><span class="price">Price: 34 Billion</span>', 34000000000, function() {}, function() {building_defs[1].base_production += 160}, 0));
	/* 16 */upgrade_defs.push(createUpgrade('heaven_gate', 5, 2, "Heavens Gate", 'Increases cultist base production by 1200.<br/><span class="price">Price: 300 Trillion</span>', 300000000000000, function() {}, function() {building_defs[1].base_production += 1200}, 0));
	/* 17 */upgrade_defs.push(createUpgrade('bad_blood', 6, 2, 'Bad Blood', 'Increases total production by 15%.<br/><span class="price">Price: 15000</span>', 15000, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 18 */upgrade_defs.push(createUpgrade('blood_bank', 7, 2, 'Blood Bank', 'Increases max blood by 50.<br/><span class="price">Price: 150000</span>', 150000, function() {}, function() {}, 2));
	/* 19 */upgrade_defs.push(createUpgrade('bloody_torch', 8, 2, 'Bloody Torch', 'Increases total production by 15%.<br/><span class="price">Price: 2 Million</span>', 2000000, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 20 */upgrade_defs.push(createUpgrade('occult_subsidies', 9, 2, 'Occult Subsidies', 'Instantly Gain 5 free cultists.<br/><span class="price">Free</span>', 0, function() {building_defs[1].count += 5}, function() {}, 2));
	/* 21 */upgrade_defs.push(createUpgrade('charging_bull', 0, 3, 'Charging Bull', 'Increases total production by 10%, and increases stock exchanges base production by 6.<br/><span class="price">Free</span>', 0, function() {}, function() {building_defs[3].base_production += 8;total_production_multiplier *= 1.1;}, 0));
	/* 22 */upgrade_defs.push(createUpgrade('fearless_girl', 1, 3, 'Fearless Girl', 'Increases total production by 10%, and increases stock exchanges base production by 20.<br/><span class="price">Free</span>', 0, function() {}, function() {building_defs[3].base_production += 20;total_production_multiplier *= 1.1;}, 0));
	/* 23 */upgrade_defs.push(createUpgrade('mutual_funds', 2, 3, 'Mutual Funds', 'Increases total production by 12%, and increases stock exchanges base production by 40.<br/><span class="price">Free</span>', 0, function() {}, function() {building_defs[3].base_production += 60;total_production_multiplier *= 1.12;}, 0));
	/* 24 */upgrade_defs.push(createUpgrade('cash_grabs', 3, 3, 'Cash Grabs', 'Increases total production by 12%, and increases stock exchanges base production by 100.<br/><span class="price">Free</span>', 0, function() {}, function() {building_defs[3].base_production += 250;total_production_multiplier *= 1.12;}, 0));
	/* 25 */upgrade_defs.push(createUpgrade('loan_sharks', 4, 3, 'Loan Sharks', 'Increases total production by 14%, and increases stock exchanges base production by 250.<br/><span class="price">Free</span>', 0, function() {}, function() {building_defs[3].base_production += 250;total_production_multiplier *= 1.14;}, 0));
	/* 26 */upgrade_defs.push(createUpgrade('gold_reserves', 5, 3, 'Gold Reserves', 'Increases total production by 14%, and increases stock exchanges base production by 900.<br/><span class="price">Free</span>', 0, function() {}, function() {building_defs[3].base_production += 900;total_production_multiplier *= 1.14;}, 0));
	/* 27 */upgrade_defs.push(createUpgrade('stable_markets', 9, 15, 'Stable Markets', 'Stock Markets Percentages no longer fluctuate but stays at its maximum value.<br/><span class="price">Free</span>', 0, function() {}, function() {}));
	/* 28 */upgrade_defs.push(createUpgrade('gold_reserves', 5, 3, 'Gold Reserves', 'Increases total production by 14%, and increases stock exchange base production by 900.<br/><span class="price">Free</span>', 0, function() {}, function() {building_defs[3].base_production += 900;total_production_multiplier *= 1.14;}));
	/* 29 */upgrade_defs.push(createUpgrade('gold_reserves', 5, 3, 'Gold Reserves', 'Increases total production by 14%, and increases stock exchange base production by 900.<br/><span class="price">Free</span>', 0, function() {}, function() {building_defs[3].base_production += 900;total_production_multiplier *= 1.14;}));
	/* 30 */upgrade_defs.push(createUpgrade('gold_reserves', 5, 3, 'Gold Reserves', 'Increases total production by 14%, and increases stock exchange base production by 900.<br/><span class="price">Free</span>', 0, function() {}, function() {building_defs[3].base_production += 900;total_production_multiplier *= 1.14;}));
	/* 31 */upgrade_defs.push(createUpgrade('deeper_mines', 0, 4, 'Deeper Mines', 'Increases mines base production by 3.<br/><span class="price">Price: 1250</span>', 1250, function() {}, function() {building_defs[4].base_production += 3}, 0));
	/* 32 */upgrade_defs.push(createUpgrade('davy_lamp', 1, 4, 'Davy Lamp', 'Increases mines base production by 12.<br/><span class="price">Price: 4000</span>', 4000, function() {}, function() {building_defs[4].base_production += 12}, 0));
	/* 33 */upgrade_defs.push(createUpgrade('better_drills', 2, 4, 'Better Drills', 'Increases mines base production by 30.<br/><span class="price">Price: 25 Million</span>', 25000000, function() {}, function() {building_defs[4].base_production += 30}, 0));
	/* 34 */upgrade_defs.push(createUpgrade('diamond_drills', 3, 4, 'Diamond Drills', 'Increases mines base production by 80.<br/><span class="price">Price: 3 Billion</span>', 3000000000, function() {}, function() {building_defs[4].base_production += 80}, 0));
	/* 35 */upgrade_defs.push(createUpgrade('bloody_mines', 4, 4, 'Bloody Mines', 'Increases mines base production by 300.<br/><span class="price">Price: 1 Trillion</span>', 1000000000000, function() {}, function() {building_defs[4].base_production += 300}, 0));
	/* 36 */upgrade_defs.push(createUpgrade('barrick_gold', 5, 4, 'Barrick Gold', 'Increases mines base production by 1500.<br/><span class="price">Price: 300 Trillion</span>', 300000000000000, function() {}, function() {building_defs[4].base_production += 1500}, 0));
	/* 37 */upgrade_defs.push(createUpgrade('piles_of_gold', 6, 4, 'Piles of Gold', 'Instantly grants 10 gold<br/><span class="price">Price: Free</span>', 0, function() {special.mine.gold += 10}, function() {}, 2));
	/* 38 */upgrade_defs.push(createUpgrade('gold_vault', 7, 4, 'Gold Vault', 'Increases production by 15%.<br/><span class="price">Price: 100000</span>', 100000, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 39 */upgrade_defs.push(createUpgrade('stacks_of_gold', 8, 4, 'Stacks of Gold', 'Decreases time it takes to mine gold by 5 minutes.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {}, 2));
	/* 40 */upgrade_defs.push(createUpgrade('gilded_mouse', 9, 4, 'Gilded Mouse', 'Increases clicking reward by 1% of production.<br/><span class="price">Price: 10 Billion</span>', 10000000000, function() {}, function() {click_production_multiplier += 0.01}, 2));
	/* 41 */upgrade_defs.push(createUpgrade('cheap_labor', 0, 5, 'Cheap Labor', 'Increases factories base production by 2.<br/><span class="price">Price: 750</span>', 750, function() {}, function() {building_defs[5].base_production += 2}, 0));
	/* 42 */upgrade_defs.push(createUpgrade('shorter_breaks', 1, 5, 'Shorter Breaks', 'Increases factories base production by 8.<br/><span class="price">Price: 10000</span>', 10000, function() {}, function() {building_defs[5].base_production += 8}, 0));
	/* 43 */upgrade_defs.push(createUpgrade('lower_wages', 2, 5, 'Lower Wages', 'Increases factories base production by 20.<br/><span class="price">Price: 2 Million</span>', 2000000, function() {}, function() {building_defs[5].base_production += 20}, 0));
	/* 44 */upgrade_defs.push(createUpgrade('union_busters', 3, 5, 'Union Busters', 'Increases factories base production by 50.<br/><span class="price">Price: 200 Million</span>', 200000000, function() {}, function() {building_defs[5].base_production += 50}, 0));
	/* 45 */upgrade_defs.push(createUpgrade('robotic_replacements', 4, 5, 'Robotic Replacements', 'Increases factories base production by 200.<br/><span class="price">Price: 30 Billion</span>', 30000000000, function() {}, function() {building_defs[5].base_production += 200}, 0));
	/* 46 */upgrade_defs.push(createUpgrade('child_labor', 5, 5, 'Child Labor', 'Increases factories base production by 1000.<br/><span class="price">Price: 300 Trillion</span>', 300000000000000, function() {}, function() {building_defs[5].base_production += 1000}, 0));
	/* 47 */upgrade_defs.push(createUpgrade('grinding_gears', 6, 5, 'Grinding Gears', 'Increases total production by 15%.<br/><span class="price">Price: 10000</span>', 10000, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 48 */upgrade_defs.push(createUpgrade('metal_mouse', 7, 5, 'Metal Mouse', 'Increases clicking reward by 1% of total production.<br/><span class="price">Price: 50000</span>', 50000, function() {}, function() {click_production_multiplier += 0.01}, 2));
	/* 49 */upgrade_defs.push(createUpgrade('conveyor_belts', 8, 5, 'Conveyor Belts', 'Increases total production by 15%.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 50 */upgrade_defs.push(createUpgrade('gearsplosion', 9, 5, 'Gearsplosion', 'Decreases gear time by 10 seconds.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {}, 2));
	/* 51 */upgrade_defs.push(createUpgrade('pok_a_tok', 0, 6, 'Pok a Tok', 'Increases temples base production by 2.<br/><span class="price">Price: 750</span>', 750, function() {}, function() {building_defs[6].base_production += 2}, 0));
	/* 52 */upgrade_defs.push(createUpgrade('religious_festivals', 1, 6, 'Religious Festivals', 'Increases temples base production by 8.<br/><span class="price">Price: 10000</span>', 10000, function() {}, function() {building_defs[6].base_production += 8}, 0));
	/* 53 */upgrade_defs.push(createUpgrade('duel_worship', 2, 6, 'Duel Worship', 'Increases temples base production by 20.<br/><span class="price">Price: 2 Million</span>', 2000000, function() {}, function() {building_defs[6].base_production += 20}, 0));
	/* 54 */upgrade_defs.push(createUpgrade('morning_star', 3, 6, 'Morning Star', 'Increases temples base production by 50.<br/><span class="price">Price: 200 Million</span>', 200000000, function() {}, function() {building_defs[6].base_production += 50}, 0));
	/* 55 */upgrade_defs.push(createUpgrade('evening_star', 4, 6, 'Evening Star', 'Increases temples base production by 200.<br/><span class="price">Price: 30 Billion</span>', 30000000000, function() {}, function() {building_defs[6].base_production += 200}, 0));
	/* 56 */upgrade_defs.push(createUpgrade('spanish_conquest', 5, 6, 'Spanish Conquest', 'Increases temples base production by 1000.<br/><span class="price">Price: 300 Trillion</span>', 300000000000000, function() {}, function() {building_defs[6].base_production += 1000}, 0));
	/* 57 */upgrade_defs.push(createUpgrade('huitzilopochtli_favor', 6, 6, 'Favor of Huitzilopochtli', 'Increases clicking reward by 1% of total production.<br/><span class="price">Price: 5 Million</span>', 5000000, function() {}, function() {click_production_multiplier += 0.01}, 2));
	/* 58 */upgrade_defs.push(createUpgrade('quetzalcoatl_favor', 7, 6, 'Favor of Quetzalcoatl', 'Decreases the cost of buildings by 2%.<br/><span class="price">Price: 5 Million</span>', 5000000, function() {}, function() {cost_multiplier /= 1.02}, 2));
	/* 59 */upgrade_defs.push(createUpgrade('tlaloc_favor', 8, 6, 'Favor of Tlaloc', 'Increases total production by 15%.<br/><span class="price">Price: 5 Million</span>', 5000000, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 60 */upgrade_defs.push(createUpgrade('tezcatlipoca_favor', 9, 6, 'Favor of Tezcatlipoca', 'Increases maximum game speed by 1.<br/><span class="price">Price: 5 Million</span>', 5000000, function() {}, function() {}, 2));
	/* 61 */upgrade_defs.push(createUpgrade('increased_machanization', 0, 7, 'Increased Machanization', 'Increases production by 5%.<br/><span class="price">Price: 10000</span>', 10000, function() {}, function() {total_production_multiplier *= 1.05}, 2));	
	/* 62 */upgrade_defs.push(createUpgrade('mechanical_enchancements', 1, 7, 'Mechanical Enchacements', 'Increases production by 0.05% per research center.<br/><span class="price">Price: 100000</span>', 100000, function() {}, function() {total_production_multiplier *= 1+0.0005*building_defs[2].count}, 2, function() {return Math.round(100*0.0005*building_defs[2].count) + "%";}));
	/* 63 */upgrade_defs.push(createUpgrade('increased_machanization_ii', 2, 7, 'Increased Machanization Mk II', 'Increases production by 5%.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {total_production_multiplier *= 1.05}, 2));	
	/* 64 */upgrade_defs.push(createUpgrade('mechanical_enchancements_ii', 3, 7, 'Mechanical Enchacements Mk II', 'Increases production by 0.05% per research center.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {total_production_multiplier *= 1+0.0005*building_defs[2].count}, 2, function() {return Math.round(100*0.0005*building_defs[2].count) + "%";}));
	/* 65 */upgrade_defs.push(createUpgrade('increased_machanization_iii', 4, 7, 'Increased Machanization Mk III', 'Increases production by 5%.<br/><span class="price">Price: 100 Million</span>', 100000000, function() {}, function() {total_production_multiplier *= 1.05}, 2));	
	/* 66 */upgrade_defs.push(createUpgrade('mechanical_enchancements_iii', 5, 7, 'Mechanical Enchacements Mk III', 'Increases production by 0.05% per research center.<br/><span class="price">Price: 1 Billion</span>', 1000000000, function() {}, function() {total_production_multiplier *= 1+0.0005*building_defs[2].count}, 2, function() {return Math.round(100*0.0005*building_defs[2].count) + "%";}));
	/* 67 */upgrade_defs.push(createUpgrade('increased_machanization_iv', 6, 7, 'Increased Machanization Mk IV', 'Increases production by 5%.<br/><span class="price">Price: 10 Billion</span>', 10000000000, function() {}, function() {total_production_multiplier *= 1.05}, 2));	
	/* 68 */upgrade_defs.push(createUpgrade('mechanical_enchancements_iv', 7, 7, 'Mechanical Enchacements Mk IV', 'Increases production by 0.05% per research center.<br/><span class="price">Price: 100 Billion</span>', 100000000000, function() {}, function() {total_production_multiplier *= 1+0.0005*building_defs[2].count}, 2, function() {return Math.round(100*0.0005*building_defs[2].count) + "%";}));
	/* 69 */upgrade_defs.push(createUpgrade('increased_machanization_v', 8, 7, 'Increased Machanization Mk V', 'Increases production by 5%.<br/><span class="price">Price: 1 Trillion</span>', 1000000000000, function() {}, function() {total_production_multiplier *= 1.05}, 2));	
	/* 70 */upgrade_defs.push(createUpgrade('mechanical_enchancements_v', 9, 7, 'Mechanical Enchacements Mk V', 'Increases production by 0.05% per research center.<br/><span class="price">Price: 10 Trillion</span>', 10000000000000, function() {}, function() {total_production_multiplier *= 1+0.0005*building_defs[2].count}, 2, function() {return Math.round(100*0.0005*building_defs[2].count) + "%";}));
	/* 71 */upgrade_defs.push(createUpgrade('blood_fountain', 0, 8, 'Fountain of Blood', 'Increases max blood by 50.<br/><span class="price">Price: 100000</span>', 100000, function() {}, function() {}, 2));
	/* 72 */upgrade_defs.push(createUpgrade('deep_mines', 1, 8, 'Deep Mines', 'Decreases mine time by 4 minutes.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {}, 2));
	/* 73 */upgrade_defs.push(createUpgrade('the_brick', 2, 8, 'The Brick', 'Increases max rolls by 2.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {}, 2));
	/* 74 */upgrade_defs.push(createUpgrade('economic_bubble', 3, 8, 'Economic Bubble', 'Increases production by 0.1% per stock market.<br/><span class="price">Price: 100 Million</span>', 100000000, function() {}, function() {total_production_multiplier *= 1+0.001*building_defs[3].count}, 2, function() {return Math.round(100*0.001*building_defs[3].count) + "%";}));
	/* 75 */upgrade_defs.push(createUpgrade('packing_tape', 4, 8, 'Packing Tape', 'Increases the production of each factory by 6 per factory.<br/><span class="price">Price: 1 Billion</span>', 1000000000, function() {}, function() {building_defs[5].base_production += building_defs[5].count * 6}, 2));
	/* 76 */upgrade_defs.push(createUpgrade('aztec_ladder', 5, 8, 'Aztec Ladder', 'Increaes the maximum favor obtainable by 50%.<br/><span class="price">Price: 10 Billion</span>', 10000000000, function() {}, function() {}, 2));
	/* 77 */upgrade_defs.push(createUpgrade('bloody_legacy', 6, 8, 'Bloody Legacy', 'Increases max blood by 1 per 5 temples, and increases the base production of temples by 4 per cultist.<br/><span class="price">Price: 100 Billion</span>', 100000000000, function() {}, function() {building_defs[6].base_production += building_defs[1].count * 4}, 2, function() {return Math.round(building_defs[6].count/5) + ", " + Math.round(building_defs[1].count*4);}));
	/* 78 */upgrade_defs.push(createUpgrade('money_mining', 7, 8, 'Money Mining', 'Stock Markets decrease mine times, and increases the max market value by 1% per 5 Mines.<br/><span class="price">Price: 1 Trillion</span>', 1000000000000, function() {}, function() {}, 2));
	/* 79 */upgrade_defs.push(createUpgrade('card_breaks', 8, 8, 'Card Breaks', 'Increases the production of each gambler by 8 per factory, and vice versa.<br/><span class="price">Price: 10 Trillion</span>', 10000000000000, function() {}, function() {building_defs[0].base_production += building_defs[5].count * 8;building_defs[5].base_production += building_defs[0].count * 8;}, 2, function() {return Math.round(building_defs[5].count*8) + ", " + Math.round(building_defs[0].count*8);}));
	/* 80 */upgrade_defs.push(createUpgrade('endless_epiphany', 9, 8, 'Endless Epiphany', 'Each research point gained from now on increases production by 1%.<br/><span class="price">Price: 100 Trillion</span>', 100000000000000, function() {}, function() {}, 2));
	/* 81 */upgrade_defs.push(createUpgrade('mad_scientists', 0, 9, 'Mad Scientists', 'Increases research centers base production by 2.<br/><span class="price">Price: Free</span>', 0, function() {}, function() {building_defs[2].base_production += 2}, 0));
	/* 82 */upgrade_defs.push(createUpgrade('flynn_effect', 1, 9, 'Flynn Effect', 'Increases research centers base production by 8.<br/><span class="price">Price: Free</span>', 0, function() {}, function() {building_defs[2].base_production += 8}, 0));	
	/* 83 */upgrade_defs.push(createUpgrade('mensa', 2, 9, 'Mensa', 'Increases research centers base production by 20.<br/><span class="price">Price: Free</span>', 0, function() {}, function() {building_defs[2].base_production += 20}, 0));
	/* 84 */upgrade_defs.push(createUpgrade('secert_labrotories', 3, 9, 'Secert Labrotories', 'Increases research centers base production by 50.<br/><span class="price">Price: Free</span>', 0, function() {}, function() {building_defs[2].base_production += 50}, 0));
	/* 85 */upgrade_defs.push(createUpgrade('proper_laboratory_attire', 4, 9, 'Proper laboratory Attire', 'Increases research centers base production by 200.<br/><span class="price">Price: Free</span>', 0, function() {}, function() {building_defs[2].base_production += 200}, 0));
	/* 86 */upgrade_defs.push(createUpgrade('big_idea', 5, 9, 'The Big Idea', 'Increases research centers base production by 1000.<br/><span class="price">Price: Free</span>', 0, function() {}, function() {building_defs[2].base_production += 1000}, 0));
	/* 87 */upgrade_defs.push(createUpgrade('smart_fingers', 6, 9, 'Smart Fingers', 'Every real 10 clicks grants an additional tick.<br/><span class="price">Price: Free</span>', 0, function() {}, function() {}, 2));
	/* 88 */upgrade_defs.push(createUpgrade('cybernectic_enhancement', 7, 9, 'Cybernectic Enhancement', 'Increases total production by 15%.<br/><span class="price">Price: Free</span>', 0, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 89 */upgrade_defs.push(createUpgrade('endless_experiments', 8, 9, 'Endless Experiments', 'Increases the time bonuses last for by 20%.<br/><span class="price">Price: Free</span>', 0, function() {}, function() {}, 2));
	/* 90 */upgrade_defs.push(createUpgrade('intelligence_booster', 9, 9, 'Itelligence Booster', 'Increases total production by 15%.<br/><span class="price">Price: Free</span>', 0, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 91 */upgrade_defs.push(createUpgrade('mouse_2', 1, 10, 'Augmented Clicking', 'Increases base clicking reward by 20.<br/><span class="price">Price: 400</span>', 400, function() {}, function() {click_production_base+=20}, 1));
	/* 92 */upgrade_defs.push(createUpgrade('mouse_3', 2, 10, 'Extreme Clicking', 'Increases base clicking reward by 100.<br/><span class="price">Price: 4000</span>', 4000, function() {}, function() {click_production_base+=100}, 1));
	/* 93 */upgrade_defs.push(createUpgrade('mouse_4', 3, 10, 'Click Workers', 'Increases base clicking reward by 1% of total production.<br/><span class="price">Price: 6000</span>', 4000, function() {}, function() {click_production_multiplier += 0.01}, 1));
	/* 94 */upgrade_defs.push(createUpgrade('mouse_5', 4, 10, 'Click Workers Mk II', 'Increases base clicking reward by 1% of total production.<br/><span class="price">Price: 40000</span>', 40000, function() {}, function() {click_production_multiplier += 0.01}, 1));
	/* 95 */upgrade_defs.push(createUpgrade('mouse_6', 5, 10, 'Click Workers Mk III', 'Increases base clicking reward by 1% of total production.<br/><span class="price">Price: 400000</span>', 400000, function() {}, function() {click_production_multiplier += 0.01}, 1));
	/* 96 */upgrade_defs.push(createUpgrade('mouse_7', 6, 10, 'Click Workers Mk IV', 'Increases base clicking reward by 1% of total production.<br/><span class="price">Price: 4 Million</span>', 4000000, function() {}, function() {click_production_multiplier += 0.01}, 1));
	/* 97 */upgrade_defs.push(createUpgrade('mouse_8', 7, 10, 'Click Workers Mk V', 'Increases base clicking reward by 1% of total production.<br/><span class="price">Price: 40 Million</span>', 40000000, function() {}, function() {click_production_multiplier += 0.01}, 1));
	/* 98 */upgrade_defs.push(createUpgrade('mouse_9', 8, 10, 'Click Workers Mk VI', 'Increases base clicking reward by 1% of total production.<br/><span class="price">Price: 400 Million</span>', 400000000, function() {}, function() {click_production_multiplier += 0.01}, 1));
	/* 99 */upgrade_defs.push(createUpgrade('mouse_10', 9, 10, 'Click Workers Mk VII', 'Increases base clicking reward by 1% of total production.<br/><span class="price">Price: 4 Billion</span>', 4000000000, function() {}, function() {click_production_multiplier += 0.01}, 1));
	/* 100 */upgrade_defs.push(createUpgrade('mouse_11', 0, 10, 'Click Workers Mk VIII', 'Increases base clicking reward by 1% of total production.<br/><span class="price">Price: 40 Billion</span>', 40000000000, function() {}, function() {click_production_multiplier += 0.01}, 1));
	/* 101 */upgrade_defs.push(createUpgrade('default_0', 0, 11, 'Futuristic Production', 'Increases production by 15%.<br/><span class="price">Price: 10000</span>', 10000, function() {}, function() {total_production_multiplier *= 1.15}, 1));
	/* 102 */upgrade_defs.push(createUpgrade('default_1', 1, 11, 'Futuristic Production Mk II', 'Increases production by 15%.<br/><span class="price">Price: 100000</span>', 100000, function() {}, function() {total_production_multiplier *= 1.15}, 1));
	/* 103 */upgrade_defs.push(createUpgrade('default_2', 2, 11, 'Futuristic Production Mk III', 'Increases production by 15%.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {total_production_multiplier *= 1.15}, 1));
	/* 104 */upgrade_defs.push(createUpgrade('default_3', 3, 11, 'Futuristic Production Mk IV', 'Increases production by 15%.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {total_production_multiplier *= 1.15}, 1));
	/* 105 */upgrade_defs.push(createUpgrade('default_4', 4, 11, 'Futuristic Production Mk V', 'Increases production by 15%.<br/><span class="price">Price: 100 Million</span>', 100000000, function() {}, function() {total_production_multiplier *= 1.15}, 1));
	/* 106 */upgrade_defs.push(createUpgrade('default_5', 5, 11, 'Futuristic Production Mk VI', 'Increases production by 15%.<br/><span class="price">Price: 1 Billion</span>', 1000000000, function() {}, function() {total_production_multiplier *= 1.15}, 1));
	/* 107 */upgrade_defs.push(createUpgrade('default_6', 6, 11, 'Futuristic Production Mk VII', 'Increases production by 15%.<br/><span class="price">Price: 10 Billion</span>', 10000000000, function() {}, function() {total_production_multiplier *= 1.15}, 1));
	/* 108 */upgrade_defs.push(createUpgrade('default_7', 7, 11, 'Futuristic Production Mk VIII', 'Increases production by 15%.<br/><span class="price">Price: 100 Billion</span>', 100000000000, function() {}, function() {total_production_multiplier *= 1.15}, 1));
	/* 109 */upgrade_defs.push(createUpgrade('default_8', 8, 11, 'Futuristic Production Mk IX', 'Increases production by 15%.<br/><span class="price">Price: 1 Trillion</span>', 1000000000000, function() {}, function() {total_production_multiplier *= 1.15}, 1));
	/* 110 */upgrade_defs.push(createUpgrade('default_9', 9, 11, 'Futuristic Production Mk X', 'Increases production by 15%.<br/><span class="price">Price: 10 Trillion</span>', 10000000000000, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 111 */upgrade_defs.push(createUpgrade('time_0', 1, 12, 'Time For Gambling', 'Increases the base production of gamblers by 1 every 2 minutes from now on.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {} , 0, function() {return Math.floor(special.gambler.time_bonus)}));
	/* 112 */upgrade_defs.push(createUpgrade('time_1', 0, 12, 'Time For Sacrifice', 'Increases the base production of cultists by 1 every 2 minutes from now on.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {}, 0, function() {return Math.floor(special.cultist.time_bonus)}));
	/* 113 */upgrade_defs.push(createUpgrade('time_2', 2, 12, 'Time For Gold', 'Increases the base production of stock markets by 1 every 2 minutes from now on.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {}, 0, function() {return Math.floor(special.stock.time_bonus)}));
	/* 114 */upgrade_defs.push(createUpgrade('time_3', 3, 12, 'Time To Mine', 'Increases the base production of mines by 1 every 2 minutes from now on.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {}, 0, function() {return Math.floor(special.mine.time_bonus)}));
	/* 115 */upgrade_defs.push(createUpgrade('time_4', 5, 12, 'Time For Genius', 'Increases the base production of research centers by 1 every 2 minutes from now on.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {}, 0, function() {return Math.floor(special.research.time_bonus)}));
	/* 116 */upgrade_defs.push(createUpgrade('time_5', 4, 12, 'Time For Labor', 'Increases the base production of factories by 1 every 2 minutes from now on.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {}, 0, function() {return Math.floor(special.factory.time_bonus)}));
	/* 117 */upgrade_defs.push(createUpgrade('time_6', 6, 12, 'Time For Worship', 'Increases the base production of temples by 1 every 2 minutes from now on.<br/><span class="price">Price: 1 Million</span>', 1000000, function() {}, function() {}, 0, function() {return Math.floor(special.temple.time_bonus)}));	
	/* 118 */upgrade_defs.push(createUpgrade('build_click_0', 1, 13, 'Gambling Mice', 'Every 100 clicks increases gambers base production by 1.<br/><span class="price">Price: 20000</span>', 20000, function() {}, function() {building_defs[0].base_production += Math.floor(stats.total_clicks/100)}, 2, function() {return Math.floor(stats.total_clicks/100)}));
	/* 119 */upgrade_defs.push(createUpgrade('build_click_1', 0, 13, 'Cultist Mice', 'Every 100 clicks increases cultist base production by 1.<br/><span class="price">Price: 20000</span>', 20000, function() {}, function() {building_defs[1].base_production += Math.floor(stats.total_clicks/100)}, 2, function() {return Math.floor(stats.total_clicks/100)}));
	/* 120 */upgrade_defs.push(createUpgrade('build_click_2', 2, 13, 'Investing Mice', 'Every 100 clicks increases stock markets base production by 1.<br/><span class="price">Price: 20000</span>', 20000, function() {}, function() {building_defs[3].base_production += Math.floor(stats.total_clicks/100)}, 2, function() {return Math.floor(stats.total_clicks/100)}));
	/* 121 */upgrade_defs.push(createUpgrade('build_click_3', 3, 13, 'Mining Mice', 'Every 100 clicks increases mines base production by 1.<br/><span class="price">Price: 20000</span>', 20000, function() {}, function() {building_defs[4].base_production += Math.floor(stats.total_clicks/100)}, 2, function() {return Math.floor(stats.total_clicks/100)}));
	/* 122 */upgrade_defs.push(createUpgrade('build_click_4', 5, 13, 'Genius Mice', 'Every 100 clicks increases research centers base production by 1.<br/><span class="price">Price: 20000</span>', 20000, function() {}, function() {building_defs[2].base_production += Math.floor(stats.total_clicks/100)}, 2, function() {return Math.floor(stats.total_clicks/100)}));
	/* 123 */upgrade_defs.push(createUpgrade('build_click_5', 4, 13, 'Slave Mice', 'Every 100 clicks increases factories base production by 1.<br/><span class="price">Price: 20000</span>', 20000, function() {}, function() {building_defs[5].base_production += Math.floor(stats.total_clicks/100)}, 2, function() {return Math.floor(stats.total_clicks/100)}));
	/* 124 */upgrade_defs.push(createUpgrade('build_click_6', 6, 13, 'Devoted Mice', 'Every 100 clicks increases temples base production by 1.<br/><span class="price">Price: 20000</span>', 20000, function() {}, function() {building_defs[6].base_production += Math.floor(stats.total_clicks/100)}, 2, function() {return Math.floor(stats.total_clicks/100)}));
	/* 125 */upgrade_defs.push(createUpgrade('additional_clicks', 0, 14, 'Additional Clicks', 'Autoclicks once per second.<br/><span class="price">Price: 10 Billion</span>', 10000000000, function() {}, function() {window.autoclicks += 1}, 1));
	/* 126 */upgrade_defs.push(createUpgrade('factory_function', 1, 14, 'Factory Function', 'Increases production by 10%.<br/><span class="price">Price: 50 Billion</span>', 50000000000, function() {}, function() {total_production_multiplier *= 1.1}, 1));
	/* 127 */upgrade_defs.push(createUpgrade('robotic_miners', 2, 14, 'Robotic Miners', 'Decreases the amount of time mines take to generate gold by 3 minutes.<br/><span class="price">Price: 250 Billion</span>', 250000000000, function() {}, function() {}, 1));
	/* 128 */upgrade_defs.push(createUpgrade('like_clockwork', 3, 14, 'Like Clockwork', 'Every 60 gears obtained increases production by 1%.<br/><span class="price">Price: 1.25 Trillion</span>', 1250000000000, function() {}, function() {total_production_multiplier *= 1 + special.factory.gears_obtained * (0.01/60)}, 1, function() {return Math.round(special.factory.gears_obtained * (0.01/60) * 100) + "%"}));
	/* 129 */upgrade_defs.push(createUpgrade('moore_research', 4, 14, 'Moore Research', 'Every 2 research centers increases production by 0.2%.<br/><span class="price">Price: 6.25 Trillion</span>', 6250000000000, function() {}, function() {total_production_multiplier *= 1 + building_defs[2].count * 0.001}, 1));
	/* 130 */upgrade_defs.push(createUpgrade('faster_production', 5, 14, 'Faster Production', 'Increases production by 10%.<br/><span class="price">Price: 10 Billion</span>', 10000000000, function() {}, function() {total_production_multiplier *= 1.1}, 1));
	/* 131 */upgrade_defs.push(createUpgrade('discount_time', 6, 14, 'Discount Time', 'Decreases building costs by 5%.<br/><span class="price">Price: 50 Billion</span>', 50000000000, function() {}, function() {cost_multiplier /= 1.05}, 1));
	/* 132 */upgrade_defs.push(createUpgrade('faster_factories', 7, 14, 'Faster Factories', 'Decreases the time it takes factories to generate gears by 5 seconds.<br/><span class="price">Price: 250 Billion</span>', 250000000000, function() {}, function() {}, 1));
	/* 133 */upgrade_defs.push(createUpgrade('liquid_time', 8, 14, 'Liquid Time', 'Increases production by 0.1% per cultist.<br/><span class="price">Price: 1.25 Trillion</span>', 1250000000000, function() {}, function() {total_production_multiplier *= 1 + building_defs[1].count * 0.001}, 1));
	/* 134 */upgrade_defs.push(createUpgrade('quick_creativity', 9, 14, 'Quick Creativity', 'Gain research points 4 Minutes Faster.<br/><span class="price">Price: 6.25 Trillion</span>', 6250000000000, function() {}, function() {}, 1));
	/* 135 */upgrade_defs.push(createUpgrade('trade_routes', 0, 15, 'Trade Routes', 'Increases production by 10%.<br/><span class="price">Price: 10 Billion</span>', 10000000000, function() {}, function() {total_production_multiplier *= 1.1}, 1));
	/* 136 */upgrade_defs.push(createUpgrade('trickle_down', 1, 15, 'Trickle Down Economics', 'Gain 1 Blood Capsule every hour.<br/><span class="price">Price: 50 Billion</span>', 50000000000, function() {}, function() {}, 1));
	/* 137 */upgrade_defs.push(createUpgrade('lucky_charms', 2, 15, 'Lucky Charm', 'Gain 1 4-leaf clover every hour.<br/><span class="price">Price: 250 Billion</span>', 250000000000, function() {}, function() {}, 1));
	/* 138 */upgrade_defs.push(createUpgrade('mechanized_machine_making', 3, 15, 'Mechanized Machine Making', 'Gain 1 machine frame every hour.<br/><span class="price">1.25 Trillion</span>', 1250000000000, function() {}, function() {}, 1));
	/* 139 */upgrade_defs.push(createUpgrade('trade_secerts', 4, 15, 'Trade Secrets', 'Increases production by 15%.<br/><span class="price">Price: 6.25 Trillion</span>', 6250000000000, function() {}, function() {total_production_multiplier *= 1.15}, 1));
	/* 140 */upgrade_defs.push(createUpgrade('rivers_of_blood', 5, 15, 'Rivers of Blood', 'Each ritual performed increases production by 1% for 10 minutes. This can stack, but does not increase time.<br/><span class="price">Price: 50 Billion</span>', 50000000000, function() {}, function() {}, 1));
	/* 141 */upgrade_defs.push(createUpgrade('storage_space', 5, 15, 'Storage Space', 'Increases maximum blood by 10.<br/><span class="price">Price: 100 Billion</span>', 100000000000, function() {}, function() {}, 1));
	/* 142 */upgrade_defs.push(createUpgrade('b_positive', 5, 15, 'B-Positive', 'Increases production by 10%.<br/><span class="price">Price: 200 Billion</span>', 200000000000, function() {}, function() {total_production_multiplier *= 1.1}, 1));
	/* 143 */upgrade_defs.push(createUpgrade('blood_flooding', 5, 15, 'Blood Flooding', 'Each ritual performed increases production by 1% for an additional 10 seconds.<br/><span class="price">Price: 400 Billion</span>', 400000000000, function() {}, function() {}, 1));
	/* 144 */upgrade_defs.push(createUpgrade('blood_debt', 5, 15, 'Blood Debt', 'Allows for the ability to go 30 blood into debt.<br/><span class="price">Price: 800 Billion</span>', 800000000000, function() {}, function() {}, 1));
	/* 145 */upgrade_defs.push(createUpgrade('gambling_addiction', 6, 15, 'Gambling Addiction', 'Increases production by 10%.<br/><span class="price">Price: 50 Billion</span>', 50000000000, function() {}, function() {total_production_multiplier *= 1.1}, 1));
	/* 146 */upgrade_defs.push(createUpgrade('rolling_in_the_dough', 6, 15, 'Rolling in the Dough', 'Each die roll increases production by 1% for 10 minutes. This can stack, but does not increase time.<br/><span class="price">Price: 100 Billion</span>', 100000000000, function() {}, function() {}, 1));
	/* 147 */upgrade_defs.push(createUpgrade('sin_city', 6, 15, 'Sin City', 'Increases maximum rolls by 1.<br/><span class="price">Price: 200 Billion</span><br><br><i>But have you heard of Den City?</i>', 200000000000, function() {}, function() {}, 1));
	/* 148 */upgrade_defs.push(createUpgrade('rigorous_cheating', 6, 15, 'Rigorous Cheating', 'Each die roll increases production by 1% for 10 seconds.<br/><span class="price">Price: 400 Billion</span>', 400000000000, function() {}, function() {}, 1));
	/* 149 */upgrade_defs.push(createUpgrade('constant_gambling', 6, 15, 'Constant Gambling', 'Reduces time for rolls to generate by 10 seconds.<br/><span class="price">Price: 800 Billion</span>', 800000000000, function() {}, function() {}, 1));
	/* 150 */upgrade_defs.push(createUpgrade('city_of_gold', 7, 15, 'City of Gold', 'Increases production by 10%.<br/><span class="price">Price: 50 Billion</span>', 50000000000, function() {}, function() {total_production_multiplier *= 1.1}, 1));
	/* 151 */upgrade_defs.push(createUpgrade('gilded_age', 7, 15, 'Gilded Age', 'Every time a gold bar is mined, production is increased by 20% for 2 minutes.<br/><span class="price">Price: 100 Billion</span>', 100000000000, function() {}, function() {}, 1));
	/* 152 */upgrade_defs.push(createUpgrade('lucky_find', 7, 15, 'Lucky Find', 'Every time a gold bar is mined, there is a 20% chance that an additional gold bar will be mined.<br/><span class="price">Price: 200 Billion</span>', 200000000000, function() {}, function() {}, 1));
	/* 153 */upgrade_defs.push(createUpgrade('solid_gold_humvee', 7, 15, 'Solid Gold Humvee', 'Increases production by 10%.<br/><span class="price">Price: 400 Billion</span>', 400000000000, function() {}, function() {total_production_multiplier *= 1.1}, 1));
	/* 154 */upgrade_defs.push(createUpgrade('roi', 7, 15, 'Return on Investment', 'Instantly grants 4 gold bars.<br/><span class="price">Price: 800 Billion</span>', 800000000000, function() {special.mine.gold += 4}, function() {}, 1));
	/* 155 */upgrade_defs.push(createUpgrade('electric_blankets', 0, 16, 'Electric Blankets', 'Increases the base production of power plants by 20000.<br/><span class="price">Price: 10 Quadrillion</span>', 1e16, function() {}, function() {building_defs[7].base_production += 20000;}, 0));
	/* 156 */upgrade_defs.push(createUpgrade('brewing_storm', 1, 16, 'Brewing Storm', 'Increases the base production of power plants by 80000.<br/><span class="price">Price: 250 Quadrillion</span>', 2.5e17, function() {}, function() {building_defs[7].base_production += 80000;}, 0));
	/* 157 */upgrade_defs.push(createUpgrade('storm_crow', 2, 16, 'Storm Crow', 'Increases the base production of power plants by 200000.<br/><span class="price">Price: 25 Quintillion</span>', 2.5e19, function() {}, function() {building_defs[7].base_production += 200000;}, 0));
	/* 158 */upgrade_defs.push(createUpgrade('constant_discharge', 3, 16, 'Constant Discharge', 'Increases the base production of power plants by 500000.<br/><span class="price">Price: 3 Sextillion</span>', 3e21, function() {}, function() {building_defs[7].base_production += 500000;}, 0));
	/* 159 */upgrade_defs.push(createUpgrade('eye_of_the_storm', 4, 16, 'Eye of the Storm', 'Increases the base production of power plants by 2000000.<br/><span class="price">Price: 300 Sextillion</span><br><i>Now im safe in the eye of the tornado</i>', 3e23, function() {}, function() {building_defs[7].base_production += 2000000;}, 0));
	/* 160 */upgrade_defs.push(createUpgrade('crow_storm', 5, 16, 'Crow Storm', 'Increases the base production of power plants by 10000000.<br/><span class="price">Price: 20 Septillion</span>', 2e25, function() {}, function() {building_defs[7].base_production += 10000000;}, 0));
	/* 161 */upgrade_defs.push(createUpgrade('powerhouse', 6, 16, 'Powerhouse', 'Increases production by 10%.<br/><span class="price">Price: 50 Quadrillion</span>', 5e16, function() {}, function() {total_production_multiplier *= 1.1;}, 2));
	/* 162 */upgrade_defs.push(createUpgrade('aaa_batteries', 7, 16, 'Triple-A Batteries', 'Increases maximum energy by 30.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 163 */upgrade_defs.push(createUpgrade('lightning_strike', 8, 16, 'Lightning Strike', 'Increases the base production of power plants by 500 per energy activation.<br/><span class="price">Price: 200 Quadrillion</span>', 2e17, function() {}, function() {}, 2));
	/* 164 */upgrade_defs.push(createUpgrade('lightning_rod', 9, 16, 'Lightning Rod', 'Increases production by 10%.<br/><span class="price">Price: 400 Quadrillion</span>', 4e17, function() {}, function() {total_production_multiplier *= 1.1;}, 2));
	/* 165 */upgrade_defs.push(createUpgrade('cloud_seeding', 0, 18, 'Cloud Seeding', 'Increases the base production of frozen wastelands by 20000.<br/><span class="price">Price: 10 Quadrillion</span>', 1e16, function() {}, function() {building_defs[9].base_production += 20000;}, 0));
	/* 166 */upgrade_defs.push(createUpgrade('climate_control', 1, 18, 'Climate Control', 'Increases the base production of frozen wastelands by 80000.<br/><span class="price">Price: 250 Quadrillion</span>', 2.5e17, function() {}, function() {building_defs[9].base_production += 80000;}, 0));
	/* 167 */upgrade_defs.push(createUpgrade('yeti_hunters', 2, 18, 'Yeti Hunters', 'Increases the base production of frozen wastelands by 200000.<br/><span class="price">Price: 25 Quintillion</span>', 2.5e19, function() {}, function() {building_defs[9].base_production += 200000;}, 0));
	/* 168 */upgrade_defs.push(createUpgrade('igloos', 3, 18, 'Igloos', 'Increases the base production of frozen wastelands by 500000.<br/><span class="price">Price: 3 Sextillion</span>', 3e21, function() {}, function() {building_defs[9].base_production += 500000;}, 0));
	/* 169 */upgrade_defs.push(createUpgrade('persevered_mammals', 4, 18, 'Perservered Mammals', 'Increases the base production of frozen wastelands by 2000000.<br/><span class="price">Price: 300 Sextillion</span>', 3e23, function() {}, function() {building_defs[9].base_production += 2000000;}, 0));
	/* 170 */upgrade_defs.push(createUpgrade('trapped_under_ice', 5, 18, 'Trapped Under Ice', 'Increases the base production of frozen wastelands by 10000000.<br/><span class="price">Price: 20 Septillion</span><br><i>No release from my cryonic state</i>', 2e25, function() {}, function() {building_defs[9].base_production += 10000000;}, 0));
	/* 171 */upgrade_defs.push(createUpgrade('ice_cold', 6, 18, 'Ice Cold', 'Snowballs gather 5 seconds faster.<br/><span class="price">Price: 50 Quadrillion</span>', 5e16, function() {}, function() {}, 2));
	/* 172 */upgrade_defs.push(createUpgrade('feet_in_the_snow', 7, 18, 'Feet in the Snow', 'Increases production by 10%.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1.1;}, 2));
	/* 173 */upgrade_defs.push(createUpgrade('abominable_snowmen', 8, 18, 'Abominable Snowmen', 'Increases production by 10%.<br/><span class="price">Price: 200 Quadrillion</span>', 2e17, function() {}, function() {total_production_multiplier *= 1.1;}, 2));
	/* 174 */upgrade_defs.push(createUpgrade('cold_hearted', 9, 18, 'Cold Hearted', 'Increases production by 75% when no buffs are active.<br/><span class="price">Price: 400 Quadrillion</span>', 4e17, function() {}, function() {buffless_multiplier *= 1.75;}, 2));
	/* 175 */upgrade_defs.push(createUpgrade('occult_worship', 0, 17, 'Occult Worship', 'Increases the base production of sacrificial shrines by 20000.<br/><span class="price">Price: 10 Quadrillion</span>', 1e16, function() {}, function() {building_defs[8].base_production += 20000;}, 0));
	/* 176 */upgrade_defs.push(createUpgrade('occult_farming', 1, 17, 'Occult Farming', 'Increases the base production of sacrificial shrines by 80000.<br/><span class="price">Price: 250 Quadrillion</span>', 2.5e17, function() {}, function() {building_defs[8].base_production += 80000;}, 0));
	/* 177 */upgrade_defs.push(createUpgrade('occult_temples', 2, 17, 'Occult Temples', 'Increases the base production of sacrificial shrines by 200000.<br/><span class="price">Price: 25 Quintillion</span>', 2.5e19, function() {}, function() {building_defs[8].base_production += 200000;}, 0));
	/* 178 */upgrade_defs.push(createUpgrade('occult_sacrifice', 3, 17, 'Sacrificial Shrines', 'Increases the base production of sacrificial shrines by 500000.<br/><span class="price">Price: 3 Sextillion</span>', 3e21, function() {}, function() {building_defs[8].base_production += 500000;}, 0));
	/* 179 */upgrade_defs.push(createUpgrade('occult_loans', 4, 17, 'Occult Loans', 'Increases the base production of sacrificial shrines by 2000000.<br/><span class="price">Price: 300 Sextillion</span><br>', 3e23, function() {}, function() {building_defs[8].base_production += 2000000;}, 0));
	/* 180 */upgrade_defs.push(createUpgrade('occult_prisoners', 5, 17, 'Occult Cells', 'Increases the base production of sacrificial shrines by 10000000.<br/><span class="price">Price: 20 Septillion</span>', 2e25, function() {}, function() {building_defs[8].base_production += 10000000;}, 0));
	/* 181 */upgrade_defs.push(createUpgrade('occult_doctors', 6, 17, 'Occult Doctors', 'Increases the base production of sacrificial shrines by 10000000.<br/><span class="price">Price: 2 Octillion</span>', 2e28, function() {}, function() {building_defs[8].base_production += 10000000;}, 0));
	/* 182 */upgrade_defs.push(createUpgrade('occult_leaders', 7, 17, 'Occult Leaders', 'Increases the base production of sacrificial shrines by 10000000.<br/><span class="price">Price: 200 Octillion</span>', 2e30, function() {}, function() {building_defs[8].base_production += 10000000;}, 0));
	/* 183 */upgrade_defs.push(createUpgrade('occult_production', 8, 17, 'Occult Production', 'Increases production by 10%.<br/><span class="price">Price: 300 Quadrillion</span>', 3e17, function() {}, function() {total_production_multiplier *= 1.1;}, 2));
	/* 184 */upgrade_defs.push(createUpgrade('occult_production_ii', 9, 17, 'Occult Production MK II', 'Increases production by 10%.<br/><span class="price">Price: 3 Quintillion</span>', 3e18, function() {}, function() {total_production_multiplier *= 1.1;}, 2));
	/* 185 */upgrade_defs.push(createUpgrade('accrued_interest', 0, 19, 'Accrued Interest', 'Increases the base production of banks by 30000.<br/><span class="price">Price: 10 Quadrillion</span>', 1e16, function() {}, function() {building_defs[10].base_production += 30000;}, 0));
	/* 186 */upgrade_defs.push(createUpgrade('billing_errors', 1, 19, 'Billing Errors', 'Increases the base production of banks by 120000.<br/><span class="price">Price: 250 Quadrillion</span>', 2.5e17, function() {}, function() {building_defs[10].base_production += 120000;}, 0));
	/* 187 */upgrade_defs.push(createUpgrade('collateral_damage', 2, 19, 'Collateral Damages', 'Increases the base production of banks by 300000.<br/><span class="price">Price: 25 Quintillion</span>', 2.5e19, function() {}, function() {building_defs[10].base_production += 300000;}, 0));
	/* 188 */upgrade_defs.push(createUpgrade('credit_cards', 3, 19, 'Credit Cards', 'Increases the base production of banks by 700000.<br/><span class="price">Price: 3 Sextillion</span>', 3e21, function() {}, function() {building_defs[10].base_production += 700000;}, 0));
	/* 189 */upgrade_defs.push(createUpgrade('mortgage', 4, 19, 'Mortgage', 'Increases the base production of banks by 2800000.<br/><span class="price">Price: 300 Sextillion</span><br>', 3e23, function() {}, function() {building_defs[10].base_production += 2800000;}, 0));
	/* 190 */upgrade_defs.push(createUpgrade('making_bank', 5, 19, 'Making Bank', 'Increases the base production of banks by 14000000.<br/><span class="price">Price: 20 Septillion</span>', 2e25, function() {}, function() {building_defs[10].base_production += 14000000;}, 0));
	/* 191 */upgrade_defs.push(createUpgrade('alien_enhancements', 0, 22, 'Alien Enhancements', 'Increases the base production of alien research facilities by 15000.<br/><span class="price">Price: 10 Quadrillion</span>', 1e16, function() {}, function() {building_defs[11].base_production += 15000;}, 0));
	/* 192 */upgrade_defs.push(createUpgrade('alien_enhancements_ii', 1, 22, 'Alien Enhancements Mk II', 'Increases the base production of alien research facilities by 60000.<br/><span class="price">Price: 250 Quadrillion</span>', 2.5e17, function() {}, function() {building_defs[11].base_production += 60000;}, 0));
	/* 193 */upgrade_defs.push(createUpgrade('alien_enhancements_iii', 2, 22, 'Alien Enhancements Mk III', 'Increases the base production of alien research facilities by 150000.<br/><span class="price">Price: 25 Quintillion</span>', 2.5e19, function() {}, function() {building_defs[11].base_production += 150000;}, 0));
	/* 194 */upgrade_defs.push(createUpgrade('alien_enhancements_iv', 3, 22, 'Alien Enhancements Mk IV', 'Increases the base production of alien research facilities by 400000.<br/><span class="price">Price: 3 Sextillion</span>', 3e21, function() {}, function() {building_defs[11].base_production += 400000;}, 0));
	/* 195 */upgrade_defs.push(createUpgrade('alien_enhancements_v', 4, 22, 'Alien Enhancements Mk V', 'Increases the base production of alien research facilities by 1500000.<br/><span class="price">Price: 300 Sextillion</span><br><i>Now im safe in the eye of the tornado</i>', 3e23, function() {}, function() {building_defs[11].base_production += 1500000;}, 0));
	/* 196 */upgrade_defs.push(createUpgrade('alien_enhancements_vi', 5, 22, 'Alien Enhancements Mk VI', 'Increases the base production of alien research facilities by 8000000.<br/><span class="price">Price: 20 Septillion</span>', 2e25, function() {}, function() {building_defs[11].base_production += 8000000;}, 0));
	/* 197 */upgrade_defs.push(createUpgrade('viscous_time', 0, 20, 'Viscous Time', 'Buffs Last 10% longer.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 198 */upgrade_defs.push(createUpgrade('extraterrestrial_learnings', 1, 20, 'Extraterrrestial Teachings', 'Increases production by 15%.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1.15}, 2));
	/* 199 */upgrade_defs.push(createUpgrade('extraterrestrial_clicking', 2, 20, 'Extraterrrestial Clicking', 'Every 10 real clicks grants 1 clock tick.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 200 */upgrade_defs.push(createUpgrade('extraterrestrial_guidelines', 3, 20, 'Extraterrrestial Guidelines', 'Increases production by 10%, this effect is compounded if no buffs are active.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1.1;buffless_multiplier *= 1.1}, 2));
	/* 201 */upgrade_defs.push(createUpgrade('mysterious_tablet_ii', 4, 20, 'Mysterious Tablet', 'Increases production by 15%.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1.15;}, 2));
	/* 202 */upgrade_defs.push(createUpgrade('endless_productivity', 5, 20, 'Endless Productivity', 'Increases production by 1% for every upgrade unlocked via alien research facilities. <br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1 + 0.01 * special.alien.upgrades_unlocked}, 2, function() {return Math.round(special.alien.upgrades_unlocked) + "%"}));
	/* 203 */upgrade_defs.push(createUpgrade('alien_speeds', 6, 20, 'Alien Speeds', 'Increases game speed by 5%. <br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 204 */upgrade_defs.push(createUpgrade('alien_formulas', 7, 20, 'Alien Formulas', 'Increases production by 15%. <br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1.15;}, 2));
	/* 205 */upgrade_defs.push(createUpgrade('mysterious_clicking', 6, 22, 'Mysterious Clicking', 'Each real click increases production by 0.4% for 60 seconds. This effect can stack, but will not increase time <br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 206 */upgrade_defs.push(createUpgrade('alien_blueprints', 8, 20, 'Alien Blueprints', 'Decreases the price of buildings by 7%. <br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {cost_multiplier /= 1.07}, 2));
	/* 207 */upgrade_defs.push(createUpgrade('alien_trade_secerts', 9, 20, 'Alien Trade secerts', 'Increases production by 15%. <br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1.15;}, 2));
	/* 208 */upgrade_defs.push(createUpgrade('alien_tomes', 10, 20, 'Alien Tomes', 'Increases production by 0.1% per temple. <br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1 + building_defs[6].count * 0.001;}, 2, function() {return Math.round(building_defs[6].count * 0.002 * 100) + "%"}));
	/* 209 */upgrade_defs.push(createUpgrade('celestial_teachings', 0, 21, 'Celestial Teachings', 'Increases production by 15%.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1.15;}, 2));
	/* 210 */upgrade_defs.push(createUpgrade('mysterious_teachings', 1, 21, 'Mysterious Teachings', 'The amount of blood debt you can go into is incresaed by 40.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 211 */upgrade_defs.push(createUpgrade('double_click', 7, 22, 'Double Click', 'Each real click has a 10% chance of being duplicated. The duplicate is counted as a real click also.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 212 */upgrade_defs.push(createUpgrade('extraterrestrial_factories', 2, 21, 'Extraterrrestial Factories', 'Factories generate gears 30% faster.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 213 */upgrade_defs.push(createUpgrade('extraterrestrial_casinos', 3, 21, 'Extraterrrestial Casinos', 'Gamblers gain rolls 30% faster.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 214 */upgrade_defs.push(createUpgrade('extraterrestrial_mines', 4, 21, 'Extraterrrestial Mines', 'Decreases the amount of time to mine a gold bar by 20%.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 215 */upgrade_defs.push(createUpgrade('extraterrestrial_mice', 8, 22, 'Extraterrrestial Mice', 'Increases the clicking reward by 2% of production.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {click_production_multiplier += 0.02}, 2));
	/* 216 */upgrade_defs.push(createUpgrade('alien_surplus', 5, 21, 'Alien Surplus', 'Increases production by 15%.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1.15;}, 2));
	/* 217 */upgrade_defs.push(createUpgrade('alien_manuscript', 6, 21, 'Mysterious Manuscript', 'Increases production by 1% for each research point gained from now on.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2, function() {return Math.round(special.research.research_bonus) + "%"}));
	/* 218 */upgrade_defs.push(createUpgrade('alien_automation', 7, 21, 'Alien Automation', 'Increases offline production by 5% of total production.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 219 */upgrade_defs.push(createUpgrade('extraterrrestial_automation', 8, 21, 'Extraterrrestial Automation', 'Increases offline production by 5% of total production.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {}, 2));
	/* 220 */upgrade_defs.push(createUpgrade('extraterrrestial_vortex', 9, 21, 'Extraterrrestial Vortex', 'Increases production by 15%.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1.15;}, 2));
	/* 221 */upgrade_defs.push(createUpgrade('wireless_mice', 9, 22, 'Wireless Mice', 'Increases the clicking reward by 2% of production.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {click_production_multiplier += 0.02}, 2));
	/* 222 */upgrade_defs.push(createUpgrade('temporal_improvemets', 8, 12, 'Temporal Improvements', 'Increases the number of available options in the temporal mastery menu by 1.<br/><span class="price">Price: 5 Quadrillion</span>', 5e15, function() {special.temporal.tasks += 1;special.temporal.max_tasks += 1;updateTemporal();}, function() {}, 1));
	/* 223 */upgrade_defs.push(createUpgrade('double_down', 0, 23, 'Double Down', 'Doubles the production of gamblers.<br/><span class="price">Price: 10 Trillion</span>', 1e13, function() {}, function() {}, 2));
	/* 224 */upgrade_defs.push(createUpgrade('double_drop', 1, 23, 'Double Drop', 'Doubles the production of cultists.<br/><span class="price">Price: 10 Trillion</span>', 1e13, function() {}, function() {}, 2));
	/* 225 */upgrade_defs.push(createUpgrade('double_stacks', 2, 23, 'Double Stacks', 'Doubles the production of stock markets.<br/><span class="price">Price: 10 Trillion</span>', 1e13, function() {}, function() {}, 2));
	/* 226 */upgrade_defs.push(createUpgrade('double_gold', 3, 23, 'Double Gold', 'Doubles the production of mines.<br/><span class="price">Price: 10 Trillion</span>', 1e13, function() {}, function() {}, 2));
	/* 227 */upgrade_defs.push(createUpgrade('double_gears', 4, 23, 'Double Gears', 'Doubles the production of factories.<br/><span class="price">Price: 10 Trillion</span>', 1e13, function() {}, function() {}, 2));
	/* 228 */upgrade_defs.push(createUpgrade('double_epiphany', 5, 23, 'Double Epiphany', 'Doubles the production of research centers.<br/><span class="price">Price: 10 Trillion</span>', 1e13, function() {}, function() {}, 2));
	/* 229 */upgrade_defs.push(createUpgrade('double_idolatry', 6, 23, 'Double Idolatry', 'Doubles the production of temples.<br/><span class="price">Price: 10 Trillion</span>', 1e13, function() {}, function() {}, 2));
	/* 230 */upgrade_defs.push(createUpgrade('deformed_time', 7, 13, 'Deformed Time', 'Increases the speed of time by 5%.<br/><span class="price">Price: 1 Billion</span>', 1000000000, function() {}, function() {}, 1));
	/* 231 */upgrade_defs.push(createUpgrade('click_combo', 8, 13, 'Click Combo', 'Every 100 real clicks increases production by 1%. This caps out at 100%.<br/><span class="price">Price: 1 Billion</span>', 1000000000, function() {}, function() {total_production_multiplier *= 1 + 0.0001 * Math.min(stats.total_real_clicks, 10000)}, 1, function() {return Math.min(Math.floor(0.1 * stats.total_real_clicks)/10, 100) + "%"}));
	/* 232 */upgrade_defs.push(createUpgrade('click_combo_ii', 9, 13, 'Click Combo Mk II', 'Every 100 real clicks increases production by 1%. This caps out at 100%.<br/><span class="price">Price: 1 Trillion</span>', 1000000000000, function() {}, function() {total_production_multiplier *= 1 + 0.0001 * Math.min(stats.total_real_clicks, 10000)}, 1, function() {return Math.min(Math.floor(0.1 * stats.total_real_clicks)/10, 100) + "%"}));
	/* 233 */upgrade_defs.push(createUpgrade('default_10', 6, 19, 'Bountiful Construction', 'Increases production by 10%, this bonus is amplified based on how many buildings are owned.<br/><span class="price">Price: 50 Billion</span>', 50000000000, function() {}, function() {total_production_multiplier *= 1.1 + Math.sqrt(stats.building_count) * 0.005}, 1, function() {return Math.floor((0.1 + Math.sqrt(stats.building_count) * 0.005) * 100) + "%"}));	
	/* 234 */upgrade_defs.push(createUpgrade('default_11', 7, 19, 'Bountiful Construction Mk II', 'Increases production by 10%, this bonus is amplified based on how many buildings are owned.<br/><span class="price">Price: 5 Trillion</span>', 5000000000000, function() {}, function() {total_production_multiplier *= 1.1 + Math.sqrt(stats.building_count) * 0.005}, 1, function() {return Math.floor((0.1 + Math.sqrt(stats.building_count) * 0.005) * 100) + "%"}));	
	/* 235 */upgrade_defs.push(createUpgrade('default_12', 8, 19, 'Bountiful Construction Mk III', 'Increases production by 10%, this bonus is amplified based on how many buildings are owned.<br/><span class="price">Price: 500 Trillion</span>', 500000000000000, function() {}, function() {total_production_multiplier *= 1.1 + Math.sqrt(stats.building_count) * 0.005}, 1, function() {return Math.floor((0.1 + Math.sqrt(stats.building_count) * 0.005) * 100) + "%"}));	
	/* 236 */upgrade_defs.push(createUpgrade('default_13', 9, 19, 'Bountiful Construction Mk IV', 'Increases production by 10%, this bonus is amplified based on how many buildings are owned.<br/><span class="price">Price: 50 Quadrillion</span>', 50000000000000000, function() {}, function() {total_production_multiplier *= 1.1 + Math.sqrt(stats.building_count) * 0.005}, 1, function() {return Math.floor((0.1 + Math.sqrt(stats.building_count) * 0.005) * 100) + "%"}));	
	/* 237 */upgrade_defs.push(createUpgrade('default_21', 0, 24, 'Intense Productivity', 'Increases production by 15%.<br/><span class="price">Price: 10 Quadrillion</span>', 1e16, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 238 */upgrade_defs.push(createUpgrade('default_22', 1, 24, 'Intense Productivity Mk II', 'Increases production by 15%.<br/><span class="price">Price: 100 Quadrillion</span>', 1e17, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 239 */upgrade_defs.push(createUpgrade('default_23', 2, 24, 'Intense Productivity Mk III', 'Increases production by 15%.<br/><span class="price">Price: 1 Quintillion</span>', 1e18, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 240 */upgrade_defs.push(createUpgrade('default_24', 3, 24, 'Intense Productivity Mk IV', 'Increases production by 15%.<br/><span class="price">Price: 10 Quintillion</span>', 1e19, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 241 */upgrade_defs.push(createUpgrade('default_25', 4, 24, 'Intense Productivity Mk V', 'Increases production by 15%.<br/><span class="price">Price: 100 Quintillion</span>', 1e20, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 242 */upgrade_defs.push(createUpgrade('default_26', 5, 24, 'Intense Productivity Mk VI', 'Increases production by 15%.<br/><span class="price">Price: 1 Sextillion</span>', 1e21, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 243 */upgrade_defs.push(createUpgrade('default_27', 6, 24, 'Intense Productivity Mk VII', 'Increases production by 15%.<br/><span class="price">Price: 10 Sextillion</span>', 1e22, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 244 */upgrade_defs.push(createUpgrade('default_28', 7, 24, 'Intense Productivity Mk VIII', 'Increases production by 15%.<br/><span class="price">Price: 100 Sextillion</span>', 1e23, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 245 */upgrade_defs.push(createUpgrade('default_29', 8, 24, 'Intense Productivity Mk IX', 'Increases production by 15%.<br/><span class="price">Price: 1 Septillion</span>', 1e24, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 246 */upgrade_defs.push(createUpgrade('default_30', 9, 24, 'Intense Productivity Mk X', 'Increases production by 15%.<br/><span class="price">Price: 10 Septillion</span>', 1e25, function() {}, function() {total_production_multiplier *= 1.15}, 1));	
	/* 247 */upgrade_defs.push(createUpgrade('default_31', 0, 25, 'Basic Dice', 'Increases production by 0.04% for each roll activated.<br/><span class="price">Price: 300</span>', 300, function() {}, function() {total_production_multiplier *= 1 + 0.0004 * special.gambler.total_rolls}, 2, function() {return Math.floor((0.04 * special.gambler.total_rolls) * 10)/10 + "%"}));	
	/* 248 */upgrade_defs.push(createUpgrade('default_32', 1, 25, 'Basic Blood', 'Increases production by 0.05% for each ritual activated.<br/><span class="price">Price: 300</span>', 300, function() {}, function() {total_production_multiplier *= 1 + 0.0005 * special.cultist.total_rituals}, 2, function() {return Math.floor((0.05 * special.cultist.total_rituals) * 10)/10 + "%"}));	
	/* 249 */upgrade_defs.push(createUpgrade('default_33', 2, 25, 'Basic Markets', 'Grants 10 ticks every time stocks markets reaches peak market value.<br/><span class="price">Price: 300</span>', 300, function() {}, function() {}, 2));	
	/* 250 */upgrade_defs.push(createUpgrade('default_34', 3, 25, 'Basic Mining', 'Clicking reward is increased by 0.5 for every other previous click, this effect is increased for every 10 mines owned.<br/><span class="price">Price: 300</span>', 300, function() {}, function() {click_production_base += 0.5 * stats.total_clicks * Math.ceil((building_defs[4].count + 1) / 10)}, 2, function() {return Math.floor(0.25 * stats.total_clicks * Math.ceil((building_defs[4].count + 1) / 10))}));	
	/* 251 */upgrade_defs.push(createUpgrade('default_35', 4, 25, 'Basic Gears', 'Increases production based on total time spent playing.<br/><span class="price">Price: 300</span>', 300, function() {}, function() {total_production_multiplier *= 1 + Math.sqrt(stats.total_time)/3000}, 2, function() {return Math.round(Math.sqrt(stats.total_time)/30 * 100)/100 + "%"}));	
	/* 252 */upgrade_defs.push(createUpgrade('default_36', 5, 25, 'Basic Worship', 'Clicking reward is increased by 4 per temple.<br/><span class="price">Price: 300</span>', 300, function() {}, function() {click_production_base+=4 * building_defs[6].count}, 2));	
	/* 253 */upgrade_defs.push(createUpgrade('default_37', 6, 25, 'Basic Research', 'Clicking reward is increased by 5 per research center.<br/><span class="price">Price: 300</span>', 300, function() {}, function() {click_production_base+=5 * building_defs[2].count}, 2));	
	/* 254 */upgrade_defs.push(createUpgrade('date_1', 0, 26, 'Just Beginning', 'Increases production by 5%.<br/><span class="price">Price: 40 Million</span>', 40000000, function() {}, function() {total_production_multiplier *= 1.05}, 3));	
	/* 255 */upgrade_defs.push(createUpgrade('date_2', 1, 26, 'Two hours later', 'Increases production by 5%.<br/><span class="price">Price: 400 Million</span>', 400000000, function() {}, function() {total_production_multiplier *= 1.05}, 3));	
	/* 256 */upgrade_defs.push(createUpgrade('date_3', 2, 26, 'Four hours later', 'Increases production by 5%.<br/><span class="price">Price: 4 Billion</span>', 4000000000, function() {}, function() {total_production_multiplier *= 1.05}, 3));	
	/* 257 */upgrade_defs.push(createUpgrade('date_4', 3, 26, 'Six hours later', 'Increases production by 5%.<br/><span class="price">Price: 40 Billion</span>', 40000000000, function() {}, function() {total_production_multiplier *= 1.05}, 3));	
	/* 258 */upgrade_defs.push(createUpgrade('date_5', 4, 26, 'Eight hours later', 'Increases production by 5%.<br/><span class="price">Price: 400 Billion</span>', 400000000000, function() {}, function() {total_production_multiplier *= 1.05}, 3));	
	/* 259 */upgrade_defs.push(createUpgrade('date_6', 5, 26, 'Ten hours later', 'Increases production by 5%.<br/><span class="price">Price: 4 Trillion</span>', 4000000000000, function() {}, function() {total_production_multiplier *= 1.05}, 3));	
	/* 260 */upgrade_defs.push(createUpgrade('date_7', 6, 26, 'Twelve hours later', 'Increases production by 5%.<br/><span class="price">Price: 40 Trillion</span>', 40000000000000, function() {}, function() {total_production_multiplier *= 1.05}, 3));	
	/* 261 */upgrade_defs.push(createUpgrade('date_8', 7, 26, 'Fourteen hours later', 'Increases production by 5%.<br/><span class="price">Price: 400 Trillion</span>', 400000000000000, function() {}, function() {total_production_multiplier *= 1.05}, 3));	
	/* 262 */upgrade_defs.push(createUpgrade('date_9', 8, 26, 'Sixteen hours later', 'Increases production by 5%.<br/><span class="price">Price: 4 Quadrillion</span>', 4000000000000000, function() {}, function() {total_production_multiplier *= 1.05}, 3));	
	/* 263 */upgrade_defs.push(createUpgrade('date_10', 9, 26, ' Eighteen hours later', 'Increases production by 5%.<br/><span class="price">Price: 40 Quadrillion</span>', 40000000000000000, function() {}, function() {total_production_multiplier *= 1.05}, 3));	
	/* 264 */upgrade_defs.push(createUpgrade('default_41', 0, 27, 'Advanced Dice', 'Every 10 real clicks decreases the amount of time to obtain the next roll by 2 seconds.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {}, 2));	
	/* 265 */upgrade_defs.push(createUpgrade('default_42', 1, 27, 'Advanced Blood', 'Increases production by 0.05% for each ritual activated.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {total_production_multiplier *= 1 + 0.0005 * special.cultist.total_rituals}, 2, function() {return Math.floor((0.05 * special.cultist.total_rituals) * 10)/10 + "%"}));	
	/* 266 */upgrade_defs.push(createUpgrade('default_43', 2, 27, 'Advanced Markets', 'Increases production by 10%.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {total_production_multiplier *= 1.1}, 2));	
	/* 267 */upgrade_defs.push(createUpgrade('default_44', 3, 27, 'Advanced Mining', 'Each real click decreases the amount of time left to mine a gold bar by 1 second. This cannot occur more than 60 times a minute.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {}, 2));	
	/* 268 */upgrade_defs.push(createUpgrade('default_45', 4, 27, 'Advanced Gears', 'Increases production based on total time spent playing.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {total_production_multiplier *= 1 + Math.sqrt(stats.total_time)/3000}, 2, function() {return Math.round(Math.sqrt(stats.total_time)/30 * 100)/100 + "%"}));	
	/* 269 */upgrade_defs.push(createUpgrade('default_46', 5, 27, 'Advanced Worship', 'Increases production by 10%.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {total_production_multiplier *= 1.1}, 2));	
	/* 270 */upgrade_defs.push(createUpgrade('default_47', 6, 27, 'Advanced Research', 'Every 2 clicks decreases the amount of time until the next research point is gained by 1.<br/><span class="price">Price: 10 Million</span>', 10000000, function() {}, function() {}, 2));	
	/* 271 */upgrade_defs.push(createUpgrade('propagranda_poster', 0, 28, 'Propaganda Poster', 'Increases the base production of propganda centers by 30000.<br/><span class="price">Price: 10 Quadrillion</span>', 1e16, function() {}, function() {building_defs[12].base_production += 30000;}, 0));
	/* 272 */upgrade_defs.push(createUpgrade('leaflet_drops', 1, 28, 'Leaflet Drops', 'Increases the base production of propganda centers by 120000.<br/><span class="price">Price: 250 Quadrillion</span>', 2.5e17, function() {}, function() {building_defs[12].base_production += 120000;}, 0));
	/* 273 */upgrade_defs.push(createUpgrade('pysocolicalical_research', 2, 28, 'Psychological Research', 'Increases the base production of propganda centers by 300000.<br/><span class="price">Price: 25 Quintillion</span>', 2.5e19, function() {}, function() {building_defs[12].base_production += 300000;}, 0));
	/* 274 */upgrade_defs.push(createUpgrade('beh_inscription', 3, 28, 'Behistun Inscription', 'Increases the base production of propganda centers by 700000.<br/><span class="price">Price: 3 Sextillion</span>', 3e21, function() {}, function() {building_defs[12].base_production += 700000;}, 0));
	/* 275 */upgrade_defs.push(createUpgrade('television_broadcasts', 4, 28, 'Television Broadcasts', 'Increases the base production of propganda centers by 2800000.<br/><span class="price">Price: 300 Sextillion</span><br>', 3e23, function() {}, function() {building_defs[12].base_production += 2800000;}, 0));
	/* 276 */upgrade_defs.push(createUpgrade('subliminal_messaging', 5, 28, 'Subliminal Messaging', 'Increases the base production of propganda centers by 14000000.<br/><span class="price">Price: 20 Septillion</span>', 2e25, function() {}, function() {building_defs[12].base_production += 14000000;}, 0));
	/* 277 */upgrade_defs.push(createUpgrade('laser_drills', 0, 29, 'Laser Drills', 'Increases the base production of asteroid miners by 1 Billion.<br/><span class="price">Price: 1 Nonillion</span>', 1e30, function() {}, function() {building_defs[13].base_production += 1000000000;}, 0));
	/* 278 */upgrade_defs.push(createUpgrade('mining_robots', 1, 29, 'Mining Robots', 'Increases the base production of asteroid miners by 4 Billion.<br/><span class="price">Price: 25 Nonillion</span>', 25e30, function() {}, function() {building_defs[13].base_production += 4000000000;}, 0));
	/* 279 */upgrade_defs.push(createUpgrade('explosive_drilling', 2, 29, 'Explosive Drilling', 'Increases the base production of asteroid miners by 10 Billion.<br/><span class="price">Price: 2 Decillion</span>', 2e33, function() {}, function() {building_defs[13].base_production += 10000000000;}, 0));
	/* 280 */upgrade_defs.push(createUpgrade('self_replication', 3, 29, 'Self Replication Mining', 'Increases the base production of asteroid miners by 25 Billion.<br/><span class="price">Price: 150 Decillion</span>', 150e33, function() {}, function() {building_defs[13].base_production += 25000000000;}, 0));
	/* 281 */upgrade_defs.push(createUpgrade('attractors', 4, 29, 'Asteroid Attractors', 'Increases the base production of asteroid miners by 100 Billion.<br/><span class="price">Price: 20 Undecillion</span>', 20e36, function() {}, function() {building_defs[13].base_production += 100000000000;}, 0));
	/* 282 */upgrade_defs.push(createUpgrade('plasma_drills', 5, 29, 'Plasma Drills', 'Increases the base production of asteroid miners by 500 Billion.<br/><span class="price">Price: 1 Duodecillion</span>', 1e39, function() {}, function() {building_defs[13].base_production += 500000000000;}, 0));	
	/* 283 */upgrade_defs.push(createUpgrade('clicking_fertalizer', 0, 30, 'Clicking Fertilizer', 'Increases the base production of click farms by 750 Million.<br/><span class="price">Price: 1 Nonillion</span>', 1e30, function() {}, function() {building_defs[14].base_production += 750000000;}, 0));
	/* 284 */upgrade_defs.push(createUpgrade('higher_click_yeilds', 1, 30, 'Higher Click Yields', 'Increases the base production of click farms by 3 Billion.<br/><span class="price">Price: 25 Nonillion</span>', 25e30, function() {}, function() {building_defs[14].base_production += 3000000000;}, 0));
	/* 285 */upgrade_defs.push(createUpgrade('click_rotation', 2, 30, 'Click Rotation', 'Increases the base production of click farms by 7.5 Billion.<br/><span class="price">Price: 2 Decillion</span>', 2e33, function() {}, function() {building_defs[14].base_production += 7500000000;}, 0));
	/* 286 */upgrade_defs.push(createUpgrade('endless_clicks', 3, 30, 'Endless Clicks', 'Increases the base production of click farms by 20 Billion.<br/><span class="price">Price: 150 Decillion</span>', 150e33, function() {}, function() {building_defs[14].base_production += 20000000000;}, 0));
	/* 287 */upgrade_defs.push(createUpgrade('genetically_modified_clicks', 4, 30, 'Genetically Modified Clicks', 'Increases the base production of click farms by 75 Billion.<br/><span class="price">Price: 20 Undecillion</span>', 20e36, function() {}, function() {building_defs[14].base_production += 75000000000;}, 0));
	/* 288 */upgrade_defs.push(createUpgrade('unethical_clicks', 5, 30, 'Unethical Clicks', 'Increases the base production of click farms by 375 Billion.<br/><span class="price">Price: 1 Duodecillion</span>', 1e39, function() {}, function() {building_defs[14].base_production += 375000000000;}, 0));	
	/* 289 */upgrade_defs.push(createUpgrade('basic_trade', 0, 31, 'Basic Trade', 'Increases the base production of merchants by 750 Million.<br/><span class="price">Price: 1 Nonillion</span>', 1e30, function() {}, function() {building_defs[15].base_production += 750000000;}, 0));
	/* 290 */upgrade_defs.push(createUpgrade('advanced_trade', 1, 31, 'Advanced Trade', 'Increases the base production of merchants by 3 Billion.<br/><span class="price">Price: 25 Nonillion</span>', 25e30, function() {}, function() {building_defs[15].base_production += 3000000000;}, 0));
	/* 291 */upgrade_defs.push(createUpgrade('neutral_trade', 2, 31, 'Neutral Trade', 'Increases the base production of merchants by 7.5 Billion.<br/><span class="price">Price: 2 Decillion</span>', 2e33, function() {}, function() {building_defs[15].base_production += 7500000000;}, 0));
	/* 292 */upgrade_defs.push(createUpgrade('wormhole_delivery', 3, 31, 'Wormhole Delivery', 'Increases the base production of merchants by 20 Billion.<br/><span class="price">Price: 150 Decillion</span>', 150e33, function() {}, function() {building_defs[15].base_production += 20000000000;}, 0));
	/* 293 */upgrade_defs.push(createUpgrade('wholesale_trade', 4, 31, 'Wholesale Trade', 'Increases the base production of merchants by 75 Billion.<br/><span class="price">Price: 20 Undecillion</span>', 20e36, function() {}, function() {building_defs[15].base_production += 75000000000;}, 0));
	/* 294 */upgrade_defs.push(createUpgrade('galactic_privateers', 5, 31, 'Galactic Privateers', 'Increases the base production of merchants by 375 Billion.<br/><span class="price">Price: 1 Duodecillion</span>', 1e39, function() {}, function() {building_defs[15].base_production += 375000000000;}, 0));	
	/* 295 */upgrade_defs.push(createUpgrade('quick_delivery', 6, 31, 'Quick Delivery', 'Decreases the amount of time it takes for a package to come by 30 seconds.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {}, 3));	
	/* 296 */upgrade_defs.push(createUpgrade('knack_for_cash', 7, 31, 'Knack for Cash', 'Increases production by 8%.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {total_production_multiplier *= 1.08}, 3));	
	/* 297 */upgrade_defs.push(createUpgrade('longevity_serum', 8, 31, 'Longevity Serum', 'Increases the duration of buffs by 5%.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {}, 3));	
	/* 298 */upgrade_defs.push(createUpgrade('expediency_serum', 9, 31, 'Expediency Serum', 'Increases game speed by 4%.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {}, 3));	
	/* 299 */upgrade_defs.push(createUpgrade('expedient_delivery', 6, 31, 'Expedient Delivery', 'Decreases the amount of time it takes for a package to come by 30 seconds.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {}, 3));	
	/* 300 */upgrade_defs.push(createUpgrade('click_package', 7, 31, 'Click Package', 'Increases clicking reward by 1% of total production.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {click_production_multiplier += 0.01}, 3));	
	/* 301 */upgrade_defs.push(createUpgrade('packaged_wealth', 8, 31, 'Packaged Wealth', 'Each time a package is obtained, 30 seconds worth of production is gained.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {}, 3));	
	/* 302 */upgrade_defs.push(createUpgrade('occult_package', 9, 31, 'Occult Package', 'Increases the maximum blood of cultists by 20.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {}, 3));	
	/* 303 */upgrade_defs.push(createUpgrade('efficiency_serum', 6, 31, 'Efficiency Serum', 'Decreases the amount of time it takes for a gear to be produced by 5 seconds.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {}, 3));	
	/* 304 */upgrade_defs.push(createUpgrade('golden_packages', 7, 31, 'Golden Packages', 'Increases production by 8%.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {total_production_multiplier *= 1.08}, 3));	
	/* 305 */upgrade_defs.push(createUpgrade('bpd', 8, 31, 'Battery Powered Delivery', 'Increases maximum power by 20.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {}, 3));	
	/* 306 */upgrade_defs.push(createUpgrade('silver_lined_packages', 9, 31, 'Silver Lined Packages', 'Increases production by 8%.<br/><span class="price">Price: 500 Octillion</span>', 5e29, function() {}, function() {total_production_multiplier *= 1.08}, 3));	

}

function htmlUpgrade(id) {
	var upgrade = upgrade_defs[id];
	var upgrade_x = -upgrade.x * 48;
	var upgrade_y = -upgrade.y * 48;
	var upgrade_tooltip_value = ""
	
	if (upgrade.tooltip_value) {upgrade_tooltip_value = "<br/>(" +upgrade.tooltip_value() + ")"}
	
	var upgrade_element = $("<div></div>");
	upgrade_element.attr("id", upgrade.id);
	upgrade_element.attr("class", "upgrade");
	upgrade_element.attr("onmouseleave", "hideTooltip()");
	upgrade_element.attr("onclick", "upgrade_defs["+id+"].buy();console.log('clicked')");
	upgrade_element.attr("onmouseover", "showTooltip(this.id, 'url(images/upgrade_sheet.png)"+upgrade_x+"px "+upgrade_y+"px', '"+upgrade.name+"', '"+upgrade.tooltip+upgrade_tooltip_value+"')");
	upgrade_element.attr("style", "float:left;height:48px;width:48px;background:url(images/upgrade_sheet.png) "+upgrade_x+"px "+upgrade_y+"px;");
	
	if (upgrade.cost > gold) {upgrade_element.css('filter','grayscale(100%)');}
	//if (upgrade.cost > gold) {upgrade_element.css('float','right)')}
	//else {upgrade_element.css('float','left)')}
	$("#leftContent").append(upgrade_element);
	
	//blueprints_bought++;
}

function displayUpgrade(id) {
	var upgrade = upgrade_defs[id];
	var upgrade_x = -upgrade.x * 48;
	var upgrade_y = -upgrade.y * 48;
	var upgrade_tooltip_value = ""
	
	if (upgrade.tooltip_value) {upgrade_tooltip_value = "<br/>(" +upgrade.tooltip_value() + ")"}
	
	var upgrade_element = $("<div></div>");
	upgrade_element.attr("id", upgrade.id);
	upgrade_element.attr("class", "upgrade");
	upgrade_element.attr("onmouseleave", "hideTooltip()");
	upgrade_element.attr("onmouseover", "showTooltip(this.id, 'url(images/upgrade_sheet.png)"+upgrade_x+"px "+upgrade_y+"px', '"+upgrade.name+"', '"+upgrade.tooltip+upgrade_tooltip_value+"')");
	upgrade_element.attr("style", "float:left;height:48px;width:48px;background:url(images/upgrade_sheet.png) "+upgrade_x+"px "+upgrade_y+"px;");
	
	$("#upgrade_list").append(upgrade_element);

}

function updateBoughtUpgrades() {
	$("#upgrades_menu").find(".upgrade").each(function(i, obj) {
		obj.remove();
	});

	for (i = 0; i < upgrade_defs.length; i++) {
		if (upgrade_defs[i].category == upgrade_category && upgrade_defs[i].bought) {
			displayUpgrade(i);
		}
	}
}

function updateUpgrades() {
	hideUpgrades();


	for (var i = 0; i < upgrade_defs.length; i++) {
		var upgrade = upgrade_defs[i];
		if (upgrade.available && !upgrade.bought && upgrade.cost < gold) {
			htmlUpgrade(i);
		}
	}	
	for (var i = 0; i < upgrade_defs.length; i++) {
		var upgrade = upgrade_defs[i];
		if (upgrade.available && !upgrade.bought && upgrade.cost >= gold) {
			htmlUpgrade(i);
		}
	}
	
	if (special.black_hole.karma_points >= 1) {$("#karma_upgrade").show();}
	else {$("#karma_upgrade").hide();}
}

function hideUpgrades() {
	$("#leftContent").find(".upgrade").each(function(i, obj) {
		if (obj.id != "karma_upgrade" && obj.id != "blueprint_upgrade" && obj.id != "tick_upgrade" && obj.id != "sacrifice_reset_menu" && obj.id != "automation_upgrade" && obj.id != "automation_menu" && obj.id != "temporal_upgrade" && obj.id != "temporal_menu" && obj.id != "trade_upgrade" && obj.id != "trade_menu") {
			obj.remove();
		}
	});
}

function autoUpgrade() {
	if (special.automation.autoupgrade) {
		for (var i = 0; i < upgrade_defs.length; i++) {
			var upgrade = upgrade_defs[i];
			if (!upgrade.bought && upgrade.available) {
				upgrade.buy();
			}
		}
	}
}